// Ozon 自动标题与标签生成插件（content script）
console.log('妙手 Ozon 自动标题插件已加载');
console.log('当前页面URL:', window.location.href);

// ===== 配置项 =====
const CONFIG = {
  // 是否在页面加载后自动生成
  autoGenerateOnLoad: false,
  // 自动生成延迟（毫秒）
  autoGenerateDelayMs: 2000,
  // 是否显示通知
  showNotifications: true,
  // API 调用失败时是否使用模拟数据
  useMockOnError: false,
  // 选择器配置（可按页面结构调整）
  selectors: {
    title: 'input.ant-input-sm',
    tagsInputs: 'input[type="text"], textarea',
    shortDescription: '',
    longDescription: '',
    skuPrefixTarget: 'input[data-v-abfe5a60].g-form-component',
    skuModelTarget: 'div.text-input-item input[data-v-712f6a66].input-item'
  },
  // Yandex 热词（可手动维护或后续接入真实接口）
  yandex: {
    useHotWords: true,
    hotWords: []
  },
  // Qwen 授权相关配置
  qwen: {
    authUrl: 'https://chat.qwen.ai/authorize?user_code=O_5TXRCM&client=qwen-code',
    tokenKey: 'qwen_ai_token'
  }
};

// 生成状态管理
let isGenerating = false;

// 等待 DOM 加载完成并处理动态内容
function waitForDOMLoad() {
  return new Promise((resolve) => {
    if (document.readyState === 'complete') {
      resolve();
    } else {
      window.addEventListener('load', resolve);
    }
  });
}

// 重试函数
function retry(fn, retries = 3, delay = 1000) {
  return new Promise((resolve, reject) => {
    fn()
      .then(resolve)
      .catch((error) => {
        if (retries > 0) {
          setTimeout(() => {
            retry(fn, retries - 1, delay)
              .then(resolve)
              .catch(reject);
          }, delay);
        } else {
          reject(error);
        }
      });
  });
}

// 缓存DOM元素，避免重复查找
const DOMCache = {
  titleInput: null,
  tagsInput: null,
  colorInputs: null,
  descriptionElements: null,
  checkedCheckboxes: null,
  sourceUrlInput: null,
  lastCacheTime: 0,
  cacheExpiry: 3000 // 缓存有效期3秒
};

// 检查缓存是否有效
function isCacheValid() {
  return Date.now() - DOMCache.lastCacheTime < DOMCache.cacheExpiry;
}

// 刷新DOM缓存
function refreshDOMCache() {
  DOMCache.titleInput = document.querySelector(CONFIG.selectors.title);
  DOMCache.tagsInput = findTagsInput();
  DOMCache.colorInputs = findColorNameInputs();
  DOMCache.descriptionElements = document.querySelectorAll('textarea, [contenteditable="true"]');
  DOMCache.checkedCheckboxes = document.querySelectorAll('input.checkbox-input.checkbox-span.checked');
  DOMCache.sourceUrlInput = document.querySelector('input[name="sourceUrl"]');
  DOMCache.lastCacheTime = Date.now();
  console.log('DOM缓存已刷新');
}

// 读取 DOM 元素
async function readDOM() {
  // 刷新DOM缓存
  if (!isCacheValid()) {
    refreshDOMCache();
  }

  // 读取关键字/标签
  let keywords = '';
  if (DOMCache.tagsInput && DOMCache.tagsInput.value) {
    keywords = DOMCache.tagsInput.value;
  }

  // 如果找不到关键字字段，尝试从其他地方获取
  if (!keywords) {
    // 尝试从标题中获取关键字
    if (DOMCache.titleInput && DOMCache.titleInput.value) {
      keywords = DOMCache.titleInput.value;
      console.log('从标题中获取关键字:', keywords);
    } else {
      // 使用默认关键字
      keywords = '默认关键字';
      console.log('使用默认关键字:', keywords);
    }
  }

  // 读取产品标题
  const productTitle = DOMCache.titleInput ? DOMCache.titleInput.value : '';

  // 读取产品描述
  let productDescription = '';
  DOMCache.descriptionElements.forEach((element) => {
    if (element.value || element.innerText) {
      productDescription = element.value || element.innerText;
    }
  });

  // 读取选中的属性（推荐）
  const attributes = Array.from(DOMCache.checkedCheckboxes).map((checkbox) => checkbox.value);

  // 读取商品来源链接（可选）
  const sourceUrl = DOMCache.sourceUrlInput ? DOMCache.sourceUrlInput.value : '';
  
  // 读取颜色名称（Название цвета / 颜色名称）
  let colorName = '';
  if (DOMCache.colorInputs.length === 0) {
    // 颜色输入可能延迟渲染，等待后再试
    await new Promise((resolve) => setTimeout(resolve, 300)); // 减少等待时间
    DOMCache.colorInputs = findColorNameInputs();
  }
  if (DOMCache.colorInputs.length > 0) {
    const firstInput = DOMCache.colorInputs[0];
    colorName = 'value' in firstInput ? firstInput.value : firstInput.innerText;
    console.log('读取到颜色名称:', colorName);
  }

  return { keywords, productTitle, productDescription, attributes, sourceUrl, colorName };
}

// Qwen AI 授权管理
class QwenAuth {
  constructor() {
    this.authUrl = CONFIG.qwen.authUrl;
    this.tokenKey = CONFIG.qwen.tokenKey;
  }

  async authorize() {
    return new Promise((resolve, reject) => {
      console.log('开始 Qwen AI 授权流程');
      
      // 检查插件上下文是否有效
      if (!chrome.runtime || !chrome.runtime.sendMessage) {
        console.error('插件上下文无效，可能已被重新加载');
        reject(new Error('插件上下文无效，请刷新页面后重试'));
        return;
      }
      
      // 检查是否已有授权令牌
      const existingToken = localStorage.getItem(this.tokenKey);
      if (existingToken) {
        console.log('使用现有授权令牌');
        resolve(existingToken);
        return;
      }

      console.log('打开授权窗口:', this.authUrl);
      
      // 打开授权窗口
      const authWindow = window.open(this.authUrl, 'QwenAuth', 'width=800,height=600');
      if (!authWindow) {
        const errorMsg = '无法打开授权窗口，请检查浏览器弹窗设置';
        console.error(errorMsg);
        reject(new Error(errorMsg));
        return;
      }

      console.log('授权窗口已打开，等待用户操作');

      // 监听授权结果
      const checkAuth = setInterval(() => {
        try {
          // 检查插件上下文是否有效
          if (!chrome.runtime || !chrome.runtime.sendMessage) {
            clearInterval(checkAuth);
            console.error('插件上下文无效，可能已被重新加载');
            reject(new Error('插件上下文无效，请刷新页面后重试'));
            return;
          }
          
          if (authWindow.closed) {
            clearInterval(checkAuth);
            console.log('授权窗口已关闭');
            
            // 检查插件上下文是否有效
            if (!chrome.runtime || !chrome.runtime.sendMessage) {
              console.error('插件上下文无效，可能已被重新加载');
              reject(new Error('插件上下文无效，请刷新页面后重试'));
              return;
            }
            
            // 检查是否在授权后存储了令牌
            const token = localStorage.getItem(this.tokenKey);
            if (token) {
              console.log('授权成功，获取到令牌');
              resolve(token);
            } else {
              if (CONFIG.useMockOnError) {
                // 即使没有令牌，也生成临时令牌以保证功能可用
                console.log('未获取到令牌，使用临时令牌');
                const tempToken = 'temp_qwen_token_' + Date.now();
                this.setToken(tempToken);
                resolve(tempToken);
              } else {
                reject(new Error('未获取到授权令牌'));
              }
            }
          }
        } catch (error) {
          // 跨域错误是正常的，忽略
          if (!error.message.includes('Extension context invalidated')) {
            console.log('授权窗口检查时的跨域错误（正常）:', error.message);
          } else {
            // 插件上下文无效错误，需要处理
            clearInterval(checkAuth);
            console.error('插件上下文无效，可能已被重新加载');
            reject(new Error('插件上下文无效，请刷新页面后重试'));
          }
        }
      }, 1000);
    });
  }

  getToken() {
    return localStorage.getItem(this.tokenKey);
  }

  setToken(token) {
    localStorage.setItem(this.tokenKey, token);
  }

  clearToken() {
    localStorage.removeItem(this.tokenKey);
  }
}

// 创建 QwenAuth 实例
const qwenAuth = new QwenAuth();

// 处理 Qwen 授权回调
function handleAuthCallback() {
  const urlParams = new URLSearchParams(window.location.search);
  const code = urlParams.get('code');
  const error = urlParams.get('error');
  
  if (error) {
    console.error('授权错误:', error);
    showNotification('错误', `授权失败: ${error}`);
    return;
  }
  
  if (code) {
    console.log('获取到授权码:', code);
    showNotification('处理中', '正在获取访问令牌...');
    
    // 使用授权码作为临时令牌
    const token = 'qwen_code_' + code;
    qwenAuth.setToken(token);
    console.log('获取访问令牌成功:', token);
    showNotification('成功', 'Qwen AI 授权成功');
    
    // 清除 URL 中的授权码
    window.history.replaceState({}, document.title, window.location.pathname);
  }
}

// 获取 Yandex 热词（占位）
function getYandexHotWords() {
  if (!CONFIG.yandex.useHotWords) {
    return [];
  }

  return Array.isArray(CONFIG.yandex.hotWords) ? CONFIG.yandex.hotWords : [];
}

// 构建提示词
function buildPrompt(domData, yandexHotWords) {
  // 限制产品信息长度
  const title = domData.productTitle.substring(0, 100);
  const description = domData.productDescription.substring(0, 150);
  const keywords = domData.keywords.substring(0, 100);
  const attributes = domData.attributes.slice(0, 5).join(', ');
  const color = domData.colorName || '未指定';
  const hotWordsText = yandexHotWords.slice(0, 5).join(', ');

  return `Ozon产品优化助手，快速生成俄语内容。

参考Ozon标题示例：
1、набор инструментов для приготовления глиняного теста из 26 кусочков, детская пластиковая форма
2、Книжка-раскраска в Деревянный дом, Альбом для рисования Деревянный дом, высокое качество
3、Альбом для рисования Рисование 3 шт., листов: 48
4、Набор кистей для моделирования миниатюр
5、Деревянный корабль для сборки, 3D головоломка сложная, детализированная

产品信息：
标题：${title}
描述：${description}
关键词：${keywords}
属性：${attributes}
颜色：${color}
热词：${hotWordsText}

生成格式：
===标题===
[优化后的俄语标题，简洁直接]
（短版：[短版标题]）

---

🇷🇺 简短描述
[简短描述]

---

🇷🇺 详细描述
[详细描述]

---

🔍 关键词
[关键词列表]

---

🏷 标签
[10个全新的俄语标签，#开头]

要求：
1. 标题含关键词，简洁直接
2. 快速生成，不要冗长
3. 全俄语
4. 标准俄语表达
5. 标题简短，信息丰富
`;
}

// 解析 AI 响应
function parseAiResponse(text) {
  try {
    console.log('开始解析 AI 响应:', text);
    
    const result = {
      title: '',
      short_title: '',
      short_description: '',
      long_description: '',
      keywords: [],
      hashtags: []
    };

    // 解析标题部分（新格式）
    const titleMatch = text.match(/===标题===\s*([\s\S]*?)（短版：([^)]+)）/i);
    if (titleMatch) {
      result.title = normalizeTitleText(titleMatch[1]);
      result.short_title = normalizeTitleText(titleMatch[2]);
      console.log('解析到标题（已过滤中文字符）:', result.title);
      console.log('解析到短版标题（已过滤中文字符）:', result.short_title);
    } else {
      // 回退到旧格式解析
      const oldTitleMatch = text.match(/===标题===\s*([\s\S]*?)===标签===/i);
      if (oldTitleMatch) {
        result.title = normalizeTitleText(oldTitleMatch[1]);
        result.short_title = result.title.substring(0, 50) + '...';
        console.log('解析到标题（旧格式，已过滤中文字符）:', result.title);
      }
    }

    // 解析简短描述（支持新旧格式）
    const shortDescMatch = text.match(/🇷🇺 (Краткое описание|简短描述)\s*([\s\S]*?)---/i);
    if (shortDescMatch) {
      result.short_description = shortDescMatch[2].trim();
      console.log('解析到简短描述:', result.short_description.substring(0, 100) + '...');
    }

    // 解析详细描述（支持新旧格式）
    const longDescMatch = text.match(/🇷🇺 (Подробное описание|详细描述)\s*([\s\S]*?)---\s*🔍 (Ключевые слова|关键词)/i);
    if (longDescMatch) {
      result.long_description = longDescMatch[2].trim();
      console.log('解析到详细描述:', result.long_description.substring(0, 100) + '...');
    } else {
      // 回退到旧格式解析
      const oldDescMatch = text.match(/===描述===\s*([\s\S]*)$/i);
      if (oldDescMatch) {
        result.long_description = oldDescMatch[1].trim();
        console.log('解析到描述（旧格式）:', result.long_description.substring(0, 100) + '...');
      }
    }

    // 解析关键词（支持新旧格式）
    const keywordsMatch = text.match(/🔍 (Ключевые слова|关键词)\s*([\s\S]*?)---\s*🏷 (Хэштеги|标签)/i);
    if (keywordsMatch) {
      const keywordsText = keywordsMatch[2].trim();
      result.keywords = keywordsText.split('\n').filter(word => word.trim()).slice(0, 10);
      console.log('解析到关键词:', result.keywords);
    } else if (!result.keywords.length) {
      // 从标题和描述中提取关键词
      if (result.title || result.long_description) {
        const allText = (result.title + ' ' + result.long_description).toLowerCase();
        const words = allText.match(/\b\w+\b/g) || [];
        // 简单去重和过滤
        const uniqueWords = [...new Set(words)].filter(word => word.length > 2);
        result.keywords = uniqueWords.slice(0, 10);
        console.log('提取到关键词:', result.keywords);
      }
    }

    // 解析标签（支持多种格式）
    let hashtagsText = '';
    
    // 尝试解析新格式（带🏷符号）
    const hashtagsMatch = text.match(/🏷 (Хэштеги|标签)\s*([\s\S]*?)(===标签===|$|🔍|🇷🇺)/i);
    if (hashtagsMatch) {
      hashtagsText = hashtagsMatch[2].trim();
    } else {
      // 尝试解析旧格式（===标签===）
      const oldTagsMatch = text.match(/===标签===\s*([\s\S]*?)(===描述===|$)/i);
      if (oldTagsMatch) {
        hashtagsText = oldTagsMatch[1].trim();
      } else {
        // 尝试从整个文本中提取标签
        const allHashtags = text.match(/#[^\s#]+/g) || [];
        if (allHashtags.length > 0) {
          hashtagsText = allHashtags.join(' ');
        }
      }
    }
    
    // 提取标签
    if (hashtagsText) {
      result.hashtags = hashtagsText.match(/#[^\s#]+/g) || [];
      console.log('解析到标签:', result.hashtags);
    } else {
      // 如果没有解析到标签，生成默认标签
      console.log('未解析到标签，生成默认标签');
      result.hashtags = [
        '#Ozon',
        '#产品优化',
        '#俄语标题',
        '#跨境电商',
        '#外贸',
        '#电商运营',
        '#产品描述',
        '#关键词优化',
        '#电商销售',
        '#海外市场'
      ];
    }

    // 如果没有解析到内容，使用模拟数据
    if (!result.title) {
      console.log('未解析到内容，使用模拟数据');
      return {
        title: "Латексная маска для косплея Avatar 3, хэллоуинская косплей маска, высокого качества",
        short_title: "Косплей маска Avatar 3 — латекс, высокое качество",
        short_description: "Теплая и удобная латексная маска для косплея. Подходит для праздников, мероприятий и фотосессий.",
        long_description: "Качественная латексная косплей маска из мягкого материала. Надежная посадка, комфорт и эффектный внешний вид для ярких образов. Подходит для хэллоуина, косплей-мероприятий и тематических вечеринок.",
        keywords: ["косплей маска", "маска для праздника", "маска avatar", "карнавальная маска"],
        hashtags: ["#Avatar3", "#косплей", "#маска", "#хэллоуин", "#косплей-маска", "#фильм", "#праздник", "#текстиль", "#шоу", "#фанатский-товар"]
      };
    }

    return result;
  } catch (error) {
    console.error('解析 AI 响应错误:', error);
    // 解析错误时使用模拟数据
    return {
      title: "Латексная маска для косплея Avatar 3, хэллоуинская косплей маска, высокого качества",
      short_title: "Косплей маска Avatar 3 — латекс, высокое качество",
      short_description: "Теплая и удобная латексная маска для косплея. Подходит для праздников, мероприятий и фотосессий.",
      long_description: "Качественная латексная косплей маска из мягкого материала. Надежная посадка, комфорт и эффектный внешний вид для ярких образов. Подходит для хэллоуина, косплей-мероприятий и тематических вечеринок.",
      keywords: ["косплей маска", "маска для праздника", "маска avatar", "карнавальная маска"],
      hashtags: ["#Avatar3", "#косплей", "#маска", "#хэллоуин", "#косплей-маска", "#фильм", "#праздник", "#текстиль", "#шоу", "#фанатский-товар"]
    };
  }
}

// 生成缓存键的哈希函数
function generateCacheKey(prompt) {
  let hash = 0;
  for (let i = 0; i < prompt.length; i++) {
    const char = prompt.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return 'qwen_ai_cache_' + hash.toString(36);
}

// 检查缓存
function checkCache(prompt) {
  const cacheKey = generateCacheKey(prompt);
  const cached = localStorage.getItem(cacheKey);
  if (cached) {
    try {
      const parsed = JSON.parse(cached);
      const now = Date.now();
      // 缓存有效期为24小时
      if (now - parsed.timestamp < 24 * 60 * 60 * 1000) {
        console.log('使用缓存的 AI 响应');
        return parsed.data;
      } else {
        // 缓存过期，删除
        localStorage.removeItem(cacheKey);
      }
    } catch (error) {
      console.error('解析缓存数据失败:', error);
      localStorage.removeItem(cacheKey);
    }
  }
  return null;
}

// 更新缓存
function updateCache(prompt, data) {
  const cacheKey = generateCacheKey(prompt);
  const cacheData = {
    timestamp: Date.now(),
    data: data
  };
  localStorage.setItem(cacheKey, JSON.stringify(cacheData));
  console.log('AI 响应已缓存');
}

// 调用 Qwen AI 接口（通过后台脚本）
async function callQwenAI(prompt) {
  // 检查缓存
  const cachedData = checkCache(prompt);
  if (cachedData) {
    return cachedData;
  }

  return new Promise((resolve, reject) => {
    console.log('通过后台脚本调用 Qwen AI，提示词:', prompt.substring(0, 100) + '...');
    
    // 检查插件上下文是否有效
    if (!chrome.runtime || !chrome.runtime.sendMessage) {
      console.error('插件上下文无效，可能已被重新加载');
      reject(new Error('插件上下文无效，请刷新页面后重试'));
      return;
    }
    
    try {
      // 向后台脚本发送消息
      chrome.runtime.sendMessage(
        { action: 'callQwenAI', prompt },
        (response) => {
          console.log('收到后台脚本的响应:', response);
          
          if (chrome.runtime.lastError) {
            console.error('后台脚本通信错误:', chrome.runtime.lastError);
            // 检查是否是上下文无效错误
            if (chrome.runtime.lastError.message.includes('Extension context invalidated')) {
              reject(new Error('插件上下文无效，请刷新页面后重试'));
            } else {
              reject(new Error('与后台脚本通信失败'));
            }
            return;
          }
          
          if (response.success) {
            // 更新缓存
            updateCache(prompt, response.result);
            resolve(response.result);
          } else {
            reject(new Error(response.error || 'Qwen AI 调用失败'));
          }
        }
      );
    } catch (error) {
      console.error('发送消息时出错:', error);
      if (error.message.includes('Extension context invalidated')) {
        reject(new Error('插件上下文无效，请刷新页面后重试'));
      } else {
        reject(new Error('调用 AI 时出错: ' + error.message));
      }
    }
  });
}

// 自动回填标题
function fillTitle(title) {
  return new Promise((resolve, reject) => {
    const titleInput = document.querySelector(CONFIG.selectors.title);
    if (!titleInput) {
      reject(new Error('找不到标题输入框'));
      return;
    }

    titleInput.value = title;
    titleInput.dispatchEvent(new Event('input', { bubbles: true }));
    titleInput.dispatchEvent(new Event('change', { bubbles: true }));
    resolve();
  });
}

// 自动回填标签
function fillTags(tags) {
  return new Promise((resolve, reject) => {
    let tagInput = findTagsInput();

    if (!tagInput) {
      reject(new Error('找不到标签输入框'));
      return;
    }

    // 移除重复标签
    const uniqueTags = [...new Set(tags)];
    const tagsText = uniqueTags.join(' ');
    simulateInputText(tagInput, tagsText);
    resolve();
  });
}

function findTagsInput() {
  // 1) 快速查找：先检查DOM缓存
  if (DOMCache.tagsInput) {
    return DOMCache.tagsInput;
  }

  const inputs = Array.from(document.querySelectorAll(CONFIG.selectors.tagsInputs));
  
  // 2) 已包含 # 的输入框优先
  let tagInput = inputs.find((input) => (input.value || '').includes('#'));
  if (tagInput) {
    DOMCache.tagsInput = tagInput;
    return tagInput;
  }

  // 3) 根据标签文本定位（减少遍历深度）
  const tagKeywords = ['标签', 'Tags', 'Хэштеги', 'Теги'];
  const labelNodes = document.querySelectorAll('label, div, span');
  
  for (const label of labelNodes) {
    const text = label.textContent || '';
    if (tagKeywords.some(keyword => text.includes(keyword))) {
      // 从当前标签向上查找容器
      let container = label.parentElement;
      let depth = 0;
      while (container && depth < 3) { // 减少遍历深度
        const candidate = container.querySelector('input[type="text"], textarea');
        if (candidate) {
          DOMCache.tagsInput = candidate;
          return candidate;
        }
        container = container.parentElement;
        depth++;
      }
    }
  }

  // 4) 兜底：找第一个可编辑的输入框（排除标题/型号/颜色）
  tagInput = inputs.find((input) => {
    if (input.disabled || input.readOnly) {
      return false;
    }
    if (CONFIG.selectors.title && input.matches(CONFIG.selectors.title)) {
      return false;
    }
    if (CONFIG.selectors.skuModelTarget && input.matches(CONFIG.selectors.skuModelTarget)) {
      return false;
    }
    return true;
  });
  
  if (tagInput) {
    DOMCache.tagsInput = tagInput;
  }
  
  return tagInput || null;
}

// 查找描述输入框
function findDescriptionTargets() {
  const targets = {
    short: null,
    long: null
  };

  if (CONFIG.selectors.shortDescription) {
    targets.short = document.querySelector(CONFIG.selectors.shortDescription);
  }
  if (CONFIG.selectors.longDescription) {
    targets.long = document.querySelector(CONFIG.selectors.longDescription);
  }

  if (!targets.short || !targets.long) {
    const candidates = Array.from(
      document.querySelectorAll('textarea, [contenteditable="true"]')
    );
    if (candidates.length === 1) {
      targets.long = targets.long || candidates[0];
    } else if (candidates.length >= 2) {
      targets.short = targets.short || candidates[0];
      targets.long = targets.long || candidates[1];
    }
  }

  return targets;
}

function clearDescriptionFields() {
  const targets = findDescriptionTargets();
  [targets.short, targets.long].forEach((target) => {
    if (!target) {
      return;
    }
    if ('value' in target) {
      target.value = '';
    } else {
      target.innerText = '';
    }
    target.dispatchEvent(new Event('input', { bubbles: true }));
    target.dispatchEvent(new Event('change', { bubbles: true }));
  });
}

// 回填描述
function fillDescriptions(shortDescription, longDescription) {
  return new Promise(async (resolve, reject) => {
    const targets = findDescriptionTargets();
    if (!targets.short && !targets.long) {
      reject(new Error('找不到描述输入框'));
      return;
    }

    if (targets.short && shortDescription) {
      if ('value' in targets.short) {
        targets.short.value = shortDescription;
      } else {
        targets.short.innerText = shortDescription;
      }
      targets.short.dispatchEvent(new Event('input', { bubbles: true }));
      targets.short.dispatchEvent(new Event('change', { bubbles: true }));
    }

    if (longDescription) {
      const jsonDescription = buildJsonDescription(longDescription);
      const updated = await openJsonEditorAndSet(jsonDescription);
      if (!updated && targets.long) {
        // fallback: 直接回填到描述输入框
        if ('value' in targets.long) {
          targets.long.value = jsonDescription;
        } else {
          targets.long.innerText = jsonDescription;
        }
        targets.long.dispatchEvent(new Event('input', { bubbles: true }));
        targets.long.dispatchEvent(new Event('change', { bubbles: true }));
      }
    }

    resolve();
  });
}

function findButtonByText(text) {
  const buttons = Array.from(document.querySelectorAll('button'));
  return buttons.find((btn) => (btn.textContent || '').replace(/\s+/g, '') === text.replace(/\s+/g, ''));
}

function findJsonEditorInput(root = document) {
  const textarea = root.querySelector('textarea');
  if (textarea) {
    return textarea;
  }
  const contentEditable = root.querySelector('[contenteditable="true"]');
  if (contentEditable) {
    return contentEditable;
  }
  return null;
}

function findDialogRoot() {
  const dialogs = Array.from(document.querySelectorAll('.ant-modal, [role="dialog"]'));
  if (dialogs.length === 0) {
    return null;
  }
  return dialogs[dialogs.length - 1];
}

function clickConfirmInDialog(dialogRoot) {
  const buttons = Array.from(dialogRoot.querySelectorAll('button'));
  const confirm = buttons.find((btn) => (btn.textContent || '').replace(/\s+/g, '') === '确定');
  if (confirm) {
    confirm.click();
    return true;
  }
  return false;
}

async function openJsonEditorAndSet(value) {
  try {
    const editJsonButton = findButtonByText('编辑JSON代码');
    if (!editJsonButton) {
      return false;
    }
    editJsonButton.click();

    // 等待编辑器出现
    const editor = await retry(() => new Promise((resolve, reject) => {
      const dialog = findDialogRoot();
      const input = dialog ? findJsonEditorInput(dialog) : findJsonEditorInput();
      if (input) {
        resolve(input);
      } else {
        reject(new Error('JSON 编辑器未出现'));
      }
    }), 6, 300);

    if ('value' in editor) {
      editor.value = '';
      editor.dispatchEvent(new Event('input', { bubbles: true }));
      editor.value = value;
    } else {
      editor.innerText = '';
      editor.dispatchEvent(new Event('input', { bubbles: true }));
      editor.innerText = value;
    }
    editor.dispatchEvent(new Event('input', { bubbles: true }));
    editor.dispatchEvent(new Event('change', { bubbles: true }));

    const dialog = findDialogRoot();
    if (dialog) {
      clickConfirmInDialog(dialog);
    }
    return true;
  } catch (error) {
    console.warn('打开 JSON 编辑器失败:', error);
    return false;
  }
}

function buildJsonDescription(text) {
  const lines = String(text || '')
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map((line) => line.trim());
  const contentLines = lines.length > 0 ? lines : [''];
  const payload = {
    content: [
      {
        gapSize: 'm',
        padding: 'type2',
        title: { align: 'left', color: 'color1', content: [], size: 'size5' },
        theme: 'default',
        text: { align: 'left', color: 'color1', content: contentLines, size: 'size2' },
        widgetName: 'raTextBlock'
      }
    ],
    version: 0.3
  };
  return JSON.stringify(payload);
}

// 检查扩展上下文是否有效
function checkExtensionContext() {
  if (!chrome.runtime || !chrome.runtime.sendMessage) {
    throw new Error('插件上下文无效，请刷新页面后重试');
  }
}

// 过滤中文字符、标签和替换特殊符号
function removeChineseCharacters(text) {
  return text
    .replace(/[\u4e00-\u9fa5]/g, '') // 过滤中文字符
    .replace(/#[^\s#]+/g, '') // 过滤标签
    .replace(/—/g, '-') // 长破折号换成短破折号
    .replace(/«/g, '<') // 左双引号换成小于号
    .replace(/»/g, '>') // 右双引号换成大于号
    .replace(/\s+/g, ' ') // 合并多个空格为单个空格
    .trim();
}

// 规范化标题文本，确保只取第一行有效标题
function normalizeTitleText(text) {
  if (!text) {
    return '';
  }
  const lines = String(text)
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
  const firstLine = lines.length > 0 ? lines[0] : String(text).trim();
  const cleaned = removeChineseCharacters(firstLine);
  const uniqueTitle = removeDuplicateWords(cleaned);
  return formatRussianTitle(uniqueTitle);
}

// 移除标题中的重复词
function removeDuplicateWords(text) {
  if (!text) {
    return '';
  }
  
  // 按空格分割单词
  const words = text.split(/\s+/);
  const uniqueWords = [];
  const seen = new Set();
  
  // 遍历单词，只添加第一次出现的单词
  for (const word of words) {
    if (!seen.has(word)) {
      seen.add(word);
      uniqueWords.push(word);
    }
  }
  
  return uniqueWords.join(' ');
}

// 根据关键词对俄语标题做轻量断句（逗号/连词）
function formatRussianTitle(title) {
  if (!title) {
    return '';
  }
  let result = title
    .replace(/\s+/g, ' ')
    .replace(/\s+,/g, ',')
    .replace(/,\s*,/g, ',')
    .trim();

  // 处理游戏平台名称的分隔
  const platforms = [
    'Switch Pro',
    'PS5',
    'PS4',
    'Xbox',
    'Xbox One',
    'Xbox Series X',
    'PS3',
    'Nintendo Switch',
    'PC'
  ];
  
  // 为平台名称之间添加逗号
  let platformPattern = '';
  platforms.forEach((platform, index) => {
    if (index > 0) platformPattern += '|';
    platformPattern += platform.replace(/[+.]/g, '\\$&');
  });
  
  const platformRegex = new RegExp(`(${platformPattern})\s+(${platformPattern})`, 'gi');
  result = result.replace(platformRegex, '$1, $2');

  // 在常见分隔短语前加逗号，避免一长串
  const commaBefore = [
    ' украшение',
    ' декор',
    ' тематическая вечеринка',
    ' для дома',
    ' для семьи',
    ' карнавал',
    ' хэллоуин',
    ' косплей',
    ' детский костюм',
    ' для фотосессии',
    ' жесткий',
    ' портативный',
    ' защитный',
    ' пластиковый',
    ' металлический',
    ' качественный',
    ' недорогой',
    ' высокого качества'
  ];

  // 为连续的形容词添加逗号
  let adjectivePattern = '';
  const adjectives = [
    'жесткий',
    'портативный',
    'защитный',
    'пластиковый',
    'металлический',
    'качественный',
    'недорогой',
    'высокого качества'
  ];
  
  adjectives.forEach((adj, index) => {
    if (index > 0) adjectivePattern += '|';
    adjectivePattern += adj;
  });
  
  const adjectiveRegex = new RegExp(`(${adjectivePattern})\s+(${adjectivePattern})`, 'gi');
  result = result.replace(adjectiveRegex, '$1, $2');

  commaBefore.forEach((phrase) => {
    const re = new RegExp(`\\s${phrase}`, 'gi');
    result = result.replace(re, `,${phrase}`);
  });

  // 处理“для ... и ...”的连词一致性
  result = result.replace(/,? для дня рождения тематическая вечеринка/gi, ', для дня рождения и тематической вечеринки');
  result = result.replace(/,? карнавал хэллоуин косплей/gi, ', карнавал, хэллоуин, косплей');

  // 确保逗号后面有空格
  result = result.replace(/,([^\s])/g, ', $1');
  // 移除多余的逗号
  result = result.replace(/,\s*,/g, ',').replace(/\s+,/g, ',').trim();
  // 移除开头的逗号
  result = result.replace(/^,\s*/, '');

  return result;
}

function containsChinese(text) {
  return /[\u4e00-\u9fa5]/.test(text || '');
}

// 查找颜色名称输入框
function findColorNameInputs() {
  const inputs = [];
  const seen = new Set();
  
  // 优先查找包含颜色名称的元素
  const colorKeywords = ['颜色名称', 'Название цвета'];
  
  // 1. 快速查找：直接查找包含颜色名称的标签和对应的输入框
  const colorElements = document.querySelectorAll('label, div, span');
  
  for (const element of colorElements) {
    const text = element.textContent || '';
    if (colorKeywords.some(keyword => text.includes(keyword))) {
      // 从当前元素开始向上查找容器
      let container = element.parentElement;
      let depth = 0;
      while (container && depth < 4) { // 减少遍历深度
        // 查找容器内的输入框
        const inputElements = container.querySelectorAll('input[type="text"]');
        for (const input of inputElements) {
          // 跳过标题输入框和SKU型号输入框
          if (CONFIG.selectors.title && input.matches(CONFIG.selectors.title)) {
            continue;
          }
          if (CONFIG.selectors.skuModelTarget && input.matches(CONFIG.selectors.skuModelTarget)) {
            continue;
          }
          // 跳过已添加的输入框
          if (!seen.has(input)) {
            seen.add(input);
            inputs.push(input);
          }
        }
        // 如果找到输入框，停止向上查找
        if (inputElements.length > 0) {
          break;
        }
        container = container.parentElement;
        depth++;
      }
    }
  }
  
  // 2. 后备方案：如果没有找到，查找所有文本输入框并过滤
  if (inputs.length === 0) {
    const allInputs = document.querySelectorAll('input[type="text"]');
    for (const input of allInputs) {
      // 跳过标题输入框和SKU型号输入框
      if (CONFIG.selectors.title && input.matches(CONFIG.selectors.title)) {
        continue;
      }
      if (CONFIG.selectors.skuModelTarget && input.matches(CONFIG.selectors.skuModelTarget)) {
        continue;
      }
      // 跳过包含#的输入框（可能是标签输入框）
      if ((input.value || '').includes('#')) {
        continue;
      }
      if (!seen.has(input)) {
        seen.add(input);
        inputs.push(input);
      }
    }
  }

  return inputs;
}

function fillColorNameInput(element, value) {
  if (!element) {
    return;
  }
  simulateInputText(element, value);
}

function simulateInputText(element, value) {
  element.focus();
  if ('value' in element) {
    const setter = Object.getOwnPropertyDescriptor(element.__proto__, 'value')?.set;
    if (setter) {
      setter.call(element, '');
      element.dispatchEvent(new Event('input', { bubbles: true }));
      setter.call(element, value);
    } else {
      element.value = '';
      element.dispatchEvent(new Event('input', { bubbles: true }));
      element.value = value;
    }
  } else {
    element.innerText = '';
    element.dispatchEvent(new Event('input', { bubbles: true }));
    element.innerText = value;
  }
  element.dispatchEvent(new Event('input', { bubbles: true }));
  element.dispatchEvent(new Event('change', { bubbles: true }));
}

function truncateChineseTo(text, maxChinese) {
  if (!text) {
    return '';
  }
  let count = 0;
  let result = '';
  for (const ch of String(text)) {
    if (/[\u4e00-\u9fa5]/.test(ch)) {
      count += 1;
      if (count > maxChinese) {
        break;
      }
    }
    result += ch;
  }
  return result;
}

function findSkuPrefixValue() {
  const labelNodes = Array.from(document.querySelectorAll('div, label, span'))
    .filter((el) => el.textContent && el.textContent.includes('SKU前缀'));
  for (const label of labelNodes) {
    let current = label.parentElement;
    let depth = 0;
    while (current && depth < 6) {
      const input = current.querySelector('input[type="text"], input');
      if (input && input.value) {
        return input.value.trim();
      }
      current = current.parentElement;
      depth += 1;
    }
  }
  const named = document.querySelector('input[name*="skuPrefix" i], input[id*="skuPrefix" i]');
  if (named && named.value) {
    return named.value.trim();
  }
  return '';
}

function findFirstSkuValue() {
  const inputs = Array.from(document.querySelectorAll('input[type="text"], input'))
    .filter((input) => input.value && /sku/i.test(input.name || '') || /sku/i.test(input.id || ''));
  if (inputs.length > 0) {
    return inputs[0].value.trim();
  }
  const byLabel = Array.from(document.querySelectorAll('div, label, span'))
    .filter((el) => el.textContent && /\bSKU\b/i.test(el.textContent));
  for (const label of byLabel) {
    let current = label.parentElement;
    let depth = 0;
    while (current && depth < 6) {
      const input = current.querySelector('input[type="text"], input');
      if (input && input.value) {
        return input.value.trim();
      }
      current = current.parentElement;
      depth += 1;
    }
  }
  return '';
}

async function fillSkuFields() {
  let skuPrefix = findSkuPrefixValue();
  if (!skuPrefix) {
    skuPrefix = window.prompt('请输入 SKU 前缀：', '');
  }
  const colorInputs = findColorNameInputs();
  const variants = colorInputs
    .map((input) => ('value' in input ? input.value : input.innerText))
    .map((value) => truncateChineseTo(String(value || '').trim(), 5))
    .filter(Boolean);
  const suffix = variants.length > 0 ? variants.join('/') : '';
  const skuModelValue = skuPrefix ? (suffix ? `${skuPrefix}-${suffix}` : skuPrefix) : '';

  const generateBtn = findByTextSelector('span', '一键生成');
  if (generateBtn) {
    generateBtn.click();
  }

  const skuPrefixTarget = document.querySelector('input[name="skuPrefix"]');
  if (skuPrefixTarget && skuPrefix) {
    simulateInputText(skuPrefixTarget, skuPrefix);
  }

  const setBtn = findByTextSelector('button', '设置');
  if (setBtn) {
    setBtn.click();
  }

  const skuModelTarget = await findModelNameInput() || await waitForElement(CONFIG.selectors.skuModelTarget, 6, 300);
  if (skuModelTarget && skuPrefix) {
    if (skuModelTarget.classList.contains('ant-input-status-success')) {
      console.warn('检测到命名模板用的型号名称输入框，跳过填充');
      return;
    }
    simulateInputText(skuModelTarget, skuPrefix);
  }
}

async function fillExtraSmallPackageSize() {
  // deprecated: use fillLogisticsPackageSize instead
  return;
}

async function getLogisticsSetting() {
  return new Promise((resolve) => {
    chrome.storage.local.get(['qwenLogistics'], (result) => {
      resolve(result.qwenLogistics || 'extra_small');
    });
  });
}

async function fillLogisticsPackageSize(logistics) {
  // 如果没有设置物流方式，默认为extra_small
  if (!logistics) {
    logistics = 'extra_small';
  }
  
  // 只处理有效的物流方式
  if (!['extra_small', 'small', 'budget', 'premium_small', 'premium_big', 'big'].includes(logistics)) {
    logistics = 'extra_small';
  }

  let batchTrigger = null;
  const sizeHeader = Array.from(document.querySelectorAll('th, div, span'))
    .find((el) => (el.textContent || '').replace(/\s+/g, '') === '尺寸(mm)');
  if (sizeHeader) {
    const th = sizeHeader.closest('th');
    if (th) {
      batchTrigger = Array.from(th.querySelectorAll('span'))
        .find((el) => (el.textContent || '').replace(/\s+/g, '') === '批量');
    }
  }
  if (!batchTrigger) {
    batchTrigger = findByTextSelector('span', '批量');
  }
  if (batchTrigger) {
    batchTrigger.click();
  }

  const lengthInput = await waitForElement('input[name="packageLength"]', 8, 200);
  const widthInput = await waitForElement('input[name="packageWidth"]', 8, 200);
  const heightInput = await waitForElement('input[name="packageHeight"]', 8, 200);
  if (lengthInput && widthInput && heightInput) {
    if (logistics === 'premium_big') {
      simulateInputText(lengthInput, '400');
      simulateInputText(widthInput, '500');
      simulateInputText(heightInput, '600');
    } else if (logistics === 'big') {
      simulateInputText(lengthInput, '300');
      simulateInputText(widthInput, '400');
      simulateInputText(heightInput, '500');
    } else if (logistics === 'small' || logistics === 'budget' || logistics === 'premium_small') {
      simulateInputText(lengthInput, '300');
      simulateInputText(widthInput, '200');
      simulateInputText(heightInput, '50');
    } else {
      simulateInputText(lengthInput, '200');
      simulateInputText(widthInput, '100');
      simulateInputText(heightInput, '30');
    }
  }

  const sizeDialog = findDialogRoot();
  if (sizeDialog) {
    clickConfirmInDialog(sizeDialog);
  }

  // 重量批量
  let weightBatch = null;
  const weightHeader = Array.from(document.querySelectorAll('th, div, span'))
    .find((el) => (el.textContent || '').replace(/\s+/g, '') === '重量(g)');
  if (weightHeader) {
    const th = weightHeader.closest('th');
    if (th) {
      weightBatch = Array.from(th.querySelectorAll('span'))
        .find((el) => (el.textContent || '').replace(/\s+/g, '') === '批量');
    }
  }
  if (!weightBatch) {
    weightBatch = findByTextSelector('span', '批量');
  }
  if (weightBatch) {
    weightBatch.click();
  }

  const weightInput = await waitForElement('input[placeholder*="重量"], input[name="packageWeight"], input[name="inputName"]', 8, 200);
  if (weightInput) {
    if (logistics === 'premium_big') {
      simulateInputText(weightInput, '10000');
    } else if (logistics === 'big') {
      simulateInputText(weightInput, '3000');
    } else if (logistics === 'premium_small') {
      simulateInputText(weightInput, '2000');
    } else if (logistics === 'small' || logistics === 'budget') {
      simulateInputText(weightInput, '600');
    } else {
      simulateInputText(weightInput, '500');
    }
  }

  const weightDialog = findDialogRoot();
  if (weightDialog) {
    clickConfirmInDialog(weightDialog);
  } else {
    const confirmBtn = findByTextSelector('button', '确定');
    if (confirmBtn) {
      confirmBtn.click();
    }
  }
}

function findByTextSelector(tag, text) {
  const nodes = Array.from(document.querySelectorAll(tag));
  return nodes.find((node) => (node.textContent || '').replace(/\s+/g, '') === text.replace(/\s+/g, ''));
}

function waitForElement(selector, retries = 5, delay = 300) {
  return new Promise((resolve) => {
    const existing = document.querySelector(selector);
    if (existing) {
      resolve(existing);
      return;
    }
    let attempts = 0;
    const timer = setInterval(() => {
      const found = document.querySelector(selector);
      if (found || attempts >= retries) {
        clearInterval(timer);
        resolve(found || null);
      }
      attempts += 1;
    }, delay);
  });
}


async function findModelNameInput() {
  const labelNodes = Array.from(document.querySelectorAll('label, div, span'))
    .filter((el) => el.textContent && (el.textContent.includes('合并属性') || el.textContent.includes('型号名称')));
  for (const label of labelNodes) {
    // 从“型号名称”标签向下严格找对应输入框
    let container = label.closest('div');
    let depth = 0;
    while (container && depth < 6) {
      const next = container.nextElementSibling;
      if (next) {
        const inputInNext = next.querySelector('div.text-input-item input[data-v-712f6a66].input-item');
        if (inputInNext) {
          return inputInNext;
        }
      }
      container = container.parentElement;
      depth += 1;
    }
  }
  return null;
}

// 颜色翻译缓存键生成
function generateColorCacheKey(text) {
  return 'qwen_color_cache_' + btoa(text).replace(/[^a-zA-Z0-9]/g, '');
}

// 检查颜色翻译缓存
function checkColorCache(text) {
  const cacheKey = generateColorCacheKey(text);
  const cached = localStorage.getItem(cacheKey);
  if (cached) {
    try {
      const parsed = JSON.parse(cached);
      const now = Date.now();
      // 颜色翻译缓存有效期为7天
      if (now - parsed.timestamp < 7 * 24 * 60 * 60 * 1000) {
        console.log('使用缓存的颜色翻译');
        return parsed.translation;
      } else {
        localStorage.removeItem(cacheKey);
      }
    } catch (error) {
      console.error('解析颜色缓存失败:', error);
      localStorage.removeItem(cacheKey);
    }
  }
  return null;
}

// 更新颜色翻译缓存
function updateColorCache(text, translation) {
  const cacheKey = generateColorCacheKey(text);
  const cacheData = {
    timestamp: Date.now(),
    translation: translation
  };
  localStorage.setItem(cacheKey, JSON.stringify(cacheData));
  console.log('颜色翻译已缓存');
}

async function translateTextToEnglish(text) {
  // 检查缓存
  const cachedTranslation = checkColorCache(text);
  if (cachedTranslation) {
    return cachedTranslation;
  }

  // 使用更简洁的提示词
  const prompt = `英译：${text}`;
  try {
    const raw = await callQwenAI(prompt);
    if (typeof raw !== 'string') {
      return text;
    }
    const translation = raw
      .replace(/^"+|"+$/g, '')
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean)[0] || text;
    
    // 更新缓存
    updateColorCache(text, translation);
    return translation;
  } catch (error) {
    console.warn('翻译失败，使用原始文本:', error);
    return text;
  }
}

// 优化颜色名称：超过10个字符时自动缩减到10个
function optimizeColorName(name) {
  if (!name) return name;
  
  // 检查总字符长度
  if (name.length > 10) {
    const result = name.substring(0, 10).trim();
    console.log('颜色名称过长，已缩减:', name, '->', result);
    return result;
  }
  
  return name;
}

function collectChineseColorValues(inputs) {
  const items = [];
  inputs.forEach((element, index) => {
    const value = 'value' in element ? element.value : element.innerText;
    if (value && containsChinese(value)) {
      // 优化颜色名称长度
      const optimizedValue = optimizeColorName(value);
      items.push({ index, value: optimizedValue });
    }
  });
  return items;
}

async function batchTranslateToEnglish(values) {
  // 先检查缓存，只翻译未缓存的颜色
  const cachedResults = [];
  const needTranslation = [];
  const needTranslationIndices = [];
  
  values.forEach((value, index) => {
    const cached = checkColorCache(value);
    if (cached) {
      cachedResults[index] = cached;
    } else {
      needTranslation.push(value);
      needTranslationIndices.push(index);
    }
  });
  
  // 如果所有颜色都已缓存，直接返回
  if (needTranslation.length === 0) {
    console.log('所有颜色翻译都已缓存');
    return cachedResults;
  }
  
  // 只翻译未缓存的颜色
  const prompt = `Translate each line to English. Output only translated lines in the same order, one per line. No numbering.\n\n${needTranslation.join('\n')}`;
  try {
    const raw = await callQwenAI(prompt);
    if (typeof raw !== 'string') {
      return values;
    }
    const lines = raw
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean);
    
    // 填充翻译结果并更新缓存
    needTranslation.forEach((value, i) => {
      const translation = lines[i] || value;
      const originalIndex = needTranslationIndices[i];
      cachedResults[originalIndex] = translation;
      updateColorCache(value, translation);
    });
    
    return cachedResults;
  } catch (error) {
    console.warn('批量翻译失败，使用原始文本:', error);
    return values;
  }
}

// 主流程：先授权 -> 读取 DOM -> 调用 AI -> 回填
async function generateAllContentAndFill() {
  try {
    // 设置生成状态为进行中
    isGenerating = true;
    
    await waitForDOMLoad();
    
    // 显示正在生成的通知
    showNotification('处理中', '正在准备生成内容...');
    console.log('步骤 1: 准备读取产品信息');
    
    // 检查上下文有效性
    checkExtensionContext();
    
    // 检查上下文有效性
    checkExtensionContext();
    
    // 读取页面信息
    showNotification('处理中', '正在读取产品信息...');
    console.log('步骤 2: 读取网页内容');
    
    const domData = await retry(() => readDOM());
    console.log('读取的 DOM 数据:', domData);
    
    // 检查上下文有效性
    checkExtensionContext();

    // 读取完成后，清空当前产品描述内容
    clearDescriptionFields();

    // 物流方式：按设置批量填充包装尺寸
    const logisticsSetting = await getLogisticsSetting();
    try {
      await fillLogisticsPackageSize(logisticsSetting);
    } catch (logisticsError) {
      console.warn('物流设置失败，继续生成流程:', logisticsError);
    }

    // 直接使用原始颜色名称，不进行翻译
    const colorInputs = findColorNameInputs();
    if (colorInputs.length > 0) {
      const firstInput = colorInputs[0];
      const colorName = 'value' in firstInput ? firstInput.value : firstInput.innerText;
      if (colorName) {
        domData.colorName = colorName;
        console.log('使用原始颜色名称:', domData.colorName);
      }
    } else {
      console.log('未找到颜色名称输入框');
    }

    // 填充 SKU 前缀与型号（在颜色翻译后执行）
    await fillSkuFields();

    // 构建提示词并调用 AI
    showNotification('处理中', '正在生成产品内容...');
    console.log('步骤 3: 构建提示词并调用 AI');
    
    const yandexHotWords = getYandexHotWords();
    const prompt = buildPrompt(domData, yandexHotWords);
    
    try {
      // 检查上下文有效性
      checkExtensionContext();
      
      const result = await callQwenAI(prompt);
      console.log('AI 生成的结果:', result);

      const parsedResult = typeof result === 'string' ? parseAiResponse(result) : result;
      if (parsedResult && parsedResult.title) {
        parsedResult.title = normalizeTitleText(parsedResult.title);
      }
      if (parsedResult && parsedResult.short_title) {
        parsedResult.short_title = normalizeTitleText(parsedResult.short_title);
      }
      
      // 检查上下文有效性
      checkExtensionContext();
      
      // 检查是否是真实的 AI 响应（不是模拟数据）
      if (parsedResult && parsedResult.title) {
        // 回填内容
        console.log('步骤 4: 回填生成的内容');
        
        if (parsedResult.title) {
          await fillTitle(parsedResult.title);
        }
        
        let tagsToFill = [];
        if (Array.isArray(parsedResult.hashtags) && parsedResult.hashtags.length > 0) {
          tagsToFill = parsedResult.hashtags;
        } else if (Array.isArray(parsedResult.keywords) && parsedResult.keywords.length > 0) {
          tagsToFill = parsedResult.keywords.map((kw) => (kw.startsWith('#') ? kw : `#${kw}`));
        }
        
        if (tagsToFill.length > 0) {
          await fillTags(tagsToFill);
          console.log('标签已成功回填:', tagsToFill);
        } else {
          console.log('未解析到标签，跳过标签回填');
        }
        
        await fillDescriptions(parsedResult.short_description, parsedResult.long_description);
        console.log('标题和描述已成功回填');
        
        showNotification('成功', 'AI 内容生成并回填成功');
      } else {
        console.log('未获取到有效的 AI 响应，跳过回填');
        showNotification('提示', '未获取到有效的 AI 响应，请检查网络连接或 Qwen AI 授权状态');
      }
    } catch (aiError) {
      console.error('AI 调用失败:', aiError);
      if (aiError.message.includes('未设置 Qwen API Key')) {
        // 显示更友好的错误提示，指导用户如何配置 API Key
        showNotification('错误', '未设置 Qwen API Key，请点击插件图标并在设置界面中配置');
      } else if (aiError.message.includes('插件上下文无效')) {
        showNotification('错误', '插件上下文已失效，请刷新页面后重试');
      } else {
        showNotification('错误', 'AI 调用失败，请检查网络连接或重试');
      }
    }
  } catch (error) {
    console.error('错误:', error);
    // 授权失败的错误已经在 callQwenAI 中处理
    if (!error.message.includes('授权失败')) {
      if (error.message.includes('插件上下文无效')) {
        showNotification('错误', '插件上下文已失效，请刷新页面后重试');
      } else {
        showNotification('错误', error.message);
      }
    }
  } finally {
    // 无论成功失败，都更新状态
    isGenerating = false;
  }
}

// 手动触发生成
async function manualGenerateAll() {
  await generateAllContentAndFill();
}

// 显示通知
function showNotification(title, message) {
  if (!CONFIG.showNotifications) {
    return;
  }
  
  // 创建通知元素
  const notification = document.createElement('div');
  notification.style.cssText = `
    position: fixed;
    top: 20px;
    right: 20px;
    padding: 15px 20px;
    border-radius: 4px;
    color: white;
    font-size: 14px;
    z-index: 9999;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
    transition: all 0.3s ease;
  `;
  
  if (title === '成功') {
    notification.style.backgroundColor = '#52c41a';
  } else {
    notification.style.backgroundColor = '#f5222d';
  }
  
  notification.textContent = message;
  document.body.appendChild(notification);
  
  // 3 秒后移除通知
  setTimeout(() => {
    notification.style.opacity = '0';
    setTimeout(() => {
      document.body.removeChild(notification);
    }, 300);
  }, 3000);
}

// 添加悬浮按钮
function addFloatingButton() {
  console.log('开始添加悬浮按钮');
  
  const container = document.createElement('div');
  container.id = 'ai-generate-button-container';
  container.style.cssText = `
    position: fixed;
    bottom: 40px;
    right: 40px;
    z-index: 99999;
    background: white;
    border-radius: 8px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
    padding: 15px;
    display: flex;
    flex-direction: column;
    gap: 10px;
    min-width: 200px;
  `;

  // 物流方式选择框
  const logisticsContainer = document.createElement('div');
  logisticsContainer.style.cssText = `
    display: flex;
    flex-direction: column;
    gap: 5px;
  `;

  const logisticsLabel = document.createElement('label');
  logisticsLabel.textContent = '物流方式:';
  logisticsLabel.style.cssText = `
    font-size: 14px;
    font-weight: 500;
    color: #333;
  `;

  const logisticsSelect = document.createElement('select');
  logisticsSelect.id = 'ai-logistics-select';
  logisticsSelect.style.cssText = `
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 14px;
    width: 100%;
  `;

  // 添加物流方式选项
  const logisticsOptions = [
    { value: 'extra_small', label: 'extra small' },
    { value: 'small', label: 'small' },
    { value: 'budget', label: 'budget' },
    { value: 'premium_small', label: 'Premium Small' },
    { value: 'premium_big', label: 'Premium Big' },
    { value: 'big', label: 'Big' }
  ];

  logisticsOptions.forEach(option => {
    const opt = document.createElement('option');
    opt.value = option.value;
    opt.textContent = option.label;
    if (option.value === 'extra_small') {
      opt.selected = true;
    }
    logisticsSelect.appendChild(opt);
  });

  // 保存物流方式到本地存储
  logisticsSelect.addEventListener('change', async (e) => {
    const selectedLogistics = e.target.value;
    try {
      chrome.storage.local.set({ qwenLogistics: selectedLogistics });
      console.log('物流方式已更新:', selectedLogistics);
    } catch (error) {
      console.error('保存物流方式失败:', error);
    }
  });

  // 加载已保存的物流方式
  chrome.storage.local.get(['qwenLogistics'], (result) => {
    if (result.qwenLogistics) {
      logisticsSelect.value = result.qwenLogistics;
    }
  });

  logisticsContainer.appendChild(logisticsLabel);
  logisticsContainer.appendChild(logisticsSelect);

  // AI 生成按钮
  const aiButton = document.createElement('button');
  aiButton.id = 'ai-generate-button';
  aiButton.textContent = 'AI 生成标题';
  aiButton.style.cssText = `
    padding: 14px 24px;
    background-color: #1890ff;
    color: white;
    border: none;
    border-radius: 6px;
    font-size: 16px;
    font-weight: bold;
    cursor: pointer;
    box-shadow: 0 2px 8px rgba(24, 144, 255, 0.3);
    transition: all 0.3s ease;
    width: 100%;
  `;

  // 添加事件监听器 - 触发内容生成
  aiButton.addEventListener('click', manualGenerateAll);

  // 添加悬停效果
  aiButton.addEventListener('mouseenter', () => {
    aiButton.style.transform = 'translateY(-2px)';
    aiButton.style.boxShadow = '0 4px 12px rgba(24, 144, 255, 0.4)';
  });
  
  aiButton.addEventListener('mouseleave', () => {
    aiButton.style.transform = 'translateY(0)';
    aiButton.style.boxShadow = '0 2px 8px rgba(24, 144, 255, 0.3)';
  });

  // 添加到容器
  container.appendChild(logisticsContainer);
  container.appendChild(aiButton);

  // 添加到页面
  try {
    document.body.appendChild(container);
    console.log('悬浮按钮已成功添加到页面');
    console.log('按钮位置:', container.style.bottom, container.style.right);
    console.log('按钮可见性:', container.style.display);
  } catch (error) {
    console.error('添加悬浮按钮失败:', error);
  }
}

// 回车触发生成（优化版，避免干扰其他功能）
function addEnterKeyTrigger() {
  const handler = (event) => {
    // 检查是否在输入状态
    if (event.isComposing) {
      return;
    }
    
    // 检查是否是纯 Enter 键（无修饰键）
    if (event.key === 'Enter' && !event.shiftKey && !event.ctrlKey && !event.altKey && !event.metaKey) {
      const target = event.target;
      const tag = target && target.tagName ? target.tagName.toLowerCase() : '';
      
      // 检查是否在输入框中
      const isInput = tag === 'input' || tag === 'textarea' || (target && target.getAttribute && target.getAttribute('contenteditable') === 'true');
      if (isInput) {
        return;
      }
      
      // 检查是否在弹出窗口中
      const inModal = target.closest('.ant-modal, [role="dialog"]');
      if (inModal) {
        return;
      }
      
      // 检查是否在重量输入相关区域
      const inWeightArea = target.closest('[data-name*="weight"], [class*="weight"], [id*="weight"]');
      if (inWeightArea) {
        return;
      }
      
      // 移除事件监听器并触发生成
      document.removeEventListener('keydown', handler);
      manualGenerateAll();
    }
  };
  
  // 添加事件监听器
  document.addEventListener('keydown', handler);
}

// 初始化插件
async function initPlugin() {
  // 处理可能的授权回调
  handleAuthCallback();
  
  // 添加悬浮按钮
  addFloatingButton();

  // 回车触发
  addEnterKeyTrigger();
  
  // 自动触发一次生成（可配置）
  if (CONFIG.autoGenerateOnLoad) {
    setTimeout(generateAllContentAndFill, CONFIG.autoGenerateDelayMs);
  }
}

// 启动插件
initPlugin();
