// Ozon 自动标题与标签生成插件（content script）

// ===== 配置项 =====
const CONFIG = {
  // 是否在页面加载后自动生成
  autoGenerateOnLoad: false,
  // 自动生成延迟（毫秒）
  autoGenerateDelayMs: 2000,
  // 是否显示通知
  showNotifications: true,
  // API 调用失败时是否使用模拟数据
  useMockOnError: false,
  // 选择器配置（可按页面结构调整）
  selectors: {
    title: 'input.ant-input-sm',
    tagsInputs: 'input[type="text"], textarea',
    shortDescription: '',
    longDescription: '',
    skuPrefixTarget: 'input[data-v-abfe5a60].g-form-component',
    skuModelTarget: 'div.text-input-item input[data-v-712f6a66].input-item'
  },
  // Yandex 热词（可手动维护或后续接入真实接口）
  yandex: {
    useHotWords: true,
    hotWords: []
  },
  // Qwen 授权相关配置
  qwen: {
    authUrl: 'https://chat.qwen.ai/authorize?user_code=O_5TXRCM&client=qwen-code',
    tokenKey: 'qwen_ai_token'
  }
};

// 生成状态管理
let isGenerating = false;

// 等待 DOM 加载完成并处理动态内容
function waitForDOMLoad() {
  return new Promise((resolve) => {
    if (document.readyState === 'complete') {
      resolve();
    } else {
      window.addEventListener('load', resolve);
    }
  });
}

// 重试函数
function retry(fn, retries = 3, delay = 1000) {
  return new Promise((resolve, reject) => {
    fn()
      .then(resolve)
      .catch((error) => {
        if (retries > 0) {
          setTimeout(() => {
            retry(fn, retries - 1, delay)
              .then(resolve)
              .catch(reject);
          }, delay);
        } else {
          reject(error);
        }
      });
  });
}

// 读取 DOM 元素
async function readDOM() {
    // 读取关键字/标签
    const tagsInput = findTagsInput();
    let keywords = '';
    if (tagsInput && tagsInput.value) {
      keywords = tagsInput.value;
    }

    // 如果找不到关键字字段，尝试从其他地方获取
    if (!keywords) {
      // 尝试从标题中获取关键字
      const titleInput = document.querySelector(CONFIG.selectors.title);
      if (titleInput && titleInput.value) {
        keywords = titleInput.value;
        console.log('从标题中获取关键字:', keywords);
      } else {
        // 使用默认关键字
        keywords = '默认关键字';
        console.log('使用默认关键字:', keywords);
      }
    }

    // 读取产品标题
    const titleInput = document.querySelector(CONFIG.selectors.title);
    const productTitle = titleInput ? titleInput.value : '';

    // 读取产品描述
    let productDescription = '';
    const descriptionElements = document.querySelectorAll('textarea, [contenteditable="true"]');
    descriptionElements.forEach((element) => {
      if (element.value || element.innerText) {
        productDescription = element.value || element.innerText;
      }
    });

    // 读取选中的属性（推荐）
    const checkedCheckboxes = document.querySelectorAll('input.checkbox-input.checkbox-span.checked');
    const attributes = Array.from(checkedCheckboxes).map((checkbox) => checkbox.value);

    // 读取商品来源链接（可选）
    const sourceUrlInput = document.querySelector('input[name="sourceUrl"]');
    const sourceUrl = sourceUrlInput ? sourceUrlInput.value : '';
    
    // 读取颜色名称（Название цвета / 颜色名称）
    let colorName = '';
    let colorInputs = findColorNameInputs();
    if (colorInputs.length === 0) {
      // 颜色输入可能延迟渲染，等待后再试
      await new Promise((resolve) => setTimeout(resolve, 500));
      colorInputs = findColorNameInputs();
    }
    if (colorInputs.length > 0) {
      const firstInput = colorInputs[0];
      colorName = 'value' in firstInput ? firstInput.value : firstInput.innerText;
      console.log('读取到颜色名称:', colorName);
    }

    return { keywords, productTitle, productDescription, attributes, sourceUrl, colorName };
}

// Qwen AI 授权管理
class QwenAuth {
  constructor() {
    this.authUrl = CONFIG.qwen.authUrl;
    this.tokenKey = CONFIG.qwen.tokenKey;
  }

  async authorize() {
    return new Promise((resolve, reject) => {
      console.log('开始 Qwen AI 授权流程');
      
      // 检查插件上下文是否有效
      if (!chrome.runtime || !chrome.runtime.sendMessage) {
        console.error('插件上下文无效，可能已被重新加载');
        reject(new Error('插件上下文无效，请刷新页面后重试'));
        return;
      }
      
      // 检查是否已有授权令牌
      const existingToken = localStorage.getItem(this.tokenKey);
      if (existingToken) {
        console.log('使用现有授权令牌');
        resolve(existingToken);
        return;
      }

      console.log('打开授权窗口:', this.authUrl);
      
      // 打开授权窗口
      const authWindow = window.open(this.authUrl, 'QwenAuth', 'width=800,height=600');
      if (!authWindow) {
        const errorMsg = '无法打开授权窗口，请检查浏览器弹窗设置';
        console.error(errorMsg);
        reject(new Error(errorMsg));
        return;
      }

      console.log('授权窗口已打开，等待用户操作');

      // 监听授权结果
      const checkAuth = setInterval(() => {
        try {
          // 检查插件上下文是否有效
          if (!chrome.runtime || !chrome.runtime.sendMessage) {
            clearInterval(checkAuth);
            console.error('插件上下文无效，可能已被重新加载');
            reject(new Error('插件上下文无效，请刷新页面后重试'));
            return;
          }
          
          if (authWindow.closed) {
            clearInterval(checkAuth);
            console.log('授权窗口已关闭');
            
            // 检查插件上下文是否有效
            if (!chrome.runtime || !chrome.runtime.sendMessage) {
              console.error('插件上下文无效，可能已被重新加载');
              reject(new Error('插件上下文无效，请刷新页面后重试'));
              return;
            }
            
            // 检查是否在授权后存储了令牌
            const token = localStorage.getItem(this.tokenKey);
            if (token) {
              console.log('授权成功，获取到令牌');
              resolve(token);
            } else {
              if (CONFIG.useMockOnError) {
                // 即使没有令牌，也生成临时令牌以保证功能可用
                console.log('未获取到令牌，使用临时令牌');
                const tempToken = 'temp_qwen_token_' + Date.now();
                this.setToken(tempToken);
                resolve(tempToken);
              } else {
                reject(new Error('未获取到授权令牌'));
              }
            }
          }
        } catch (error) {
          // 跨域错误是正常的，忽略
          if (!error.message.includes('Extension context invalidated')) {
            console.log('授权窗口检查时的跨域错误（正常）:', error.message);
          } else {
            // 插件上下文无效错误，需要处理
            clearInterval(checkAuth);
            console.error('插件上下文无效，可能已被重新加载');
            reject(new Error('插件上下文无效，请刷新页面后重试'));
          }
        }
      }, 1000);
    });
  }

  getToken() {
    return localStorage.getItem(this.tokenKey);
  }

  setToken(token) {
    localStorage.setItem(this.tokenKey, token);
  }

  clearToken() {
    localStorage.removeItem(this.tokenKey);
  }
}

// 创建 QwenAuth 实例
const qwenAuth = new QwenAuth();

// 处理 Qwen 授权回调
function handleAuthCallback() {
  const urlParams = new URLSearchParams(window.location.search);
  const code = urlParams.get('code');
  const error = urlParams.get('error');
  
  if (error) {
    console.error('授权错误:', error);
    showNotification('错误', `授权失败: ${error}`);
    return;
  }
  
  if (code) {
    console.log('获取到授权码:', code);
    showNotification('处理中', '正在获取访问令牌...');
    
    // 使用授权码作为临时令牌
    const token = 'qwen_code_' + code;
    qwenAuth.setToken(token);
    console.log('获取访问令牌成功:', token);
    showNotification('成功', 'Qwen AI 授权成功');
    
    // 清除 URL 中的授权码
    window.history.replaceState({}, document.title, window.location.pathname);
  }
}

// 获取 Yandex 热词（占位）
function getYandexHotWords() {
  if (!CONFIG.yandex.useHotWords) {
    return [];
  }

  return Array.isArray(CONFIG.yandex.hotWords) ? CONFIG.yandex.hotWords : [];
}

// 构建提示词
function buildPrompt(domData, yandexHotWords) {
  const hotWordsText = yandexHotWords.length > 0 ? yandexHotWords.join(', ') : '无';

  return `你现在是个ozon标题助手，严格参考示例模板与格式输出，结合yandex热词,标题里不能带有 符号：— «»

【产品信息】
当前标题：${domData.productTitle}
产品描述：${domData.productDescription}
关键词：${domData.keywords}
属性：${domData.attributes.join(', ')}
链接：${domData.sourceUrl}
颜色名称：${domData.colorName || '未指定'}

【Yandex 热词】
${hotWordsText}

【示例模板（必须遵循此格式与语气）】
kЛегкосплавный диск для Toyota RAV4 (Rongfang), 18x7 дюймов, 5x114.3 ET35 D60.1, оригинальный дизайн, комплект 1 шт. 

🇷🇺 Краткое описание
Стильный легкосплавный диск, разработанный для Toyota RAV4 (включая модели Rongfang/Huatai). Размер 18x7 дюймов, параметры: PCD 5x114.3, вылет ET35, центральное отверстие D60.1. Оригинальный дизайн, соответствует заводским стандартам. Продается поштучно.

🇷🇺 Подробное описание
🛞 Обновите внешний вид и управляемость вашего Toyota RAV4 с этим оригинальным диском!

Этот легкосплавный диск специально создан с учетом дизайна и технических требований для Toyota RAV4, включая версии Rongfang и Huatai. Он не только придаст вашему автомобилю современный и стильный облик, но и благодаря точному соответствию параметрам обеспечит безопасность и комфорт вождения.

⭐ Ключевые характеристики:

📐 Точные параметры для идеальной посадки:

Диаметр и ширина: 18 x 7 дюймов — популярный и сбалансированный размер для RAV4.

PCD (разболтовка): 5 x 114.3 мм — стандартный для многих моделей Toyota, включая RAV4.

Вылет (ET): ET35 — обеспечивает правильное положение колеса в арке, сохраняя управляемость.

Центральное отверстие (DIA, ЦО): D60.1 мм — точное совпадение со ступицей Toyota, что важно для правильной центровки.

🛡️ Надежность и совместимость:

Оригинальный дизайн: Внешний вид соответствует заводскому стилю, что позволяет сохранить или улучшить экстерьер автомобиля.

Проверенная совместимость: Подходит для Toyota RAV4 (также может подойти для других моделей Toyota с аналогичными параметрами — рекомендуется уточнить).

Продается поштучно: Вы можете купить один диск для замены или полный комплект (4 шт.) для полного обновления.

💡 Важная информация для покупателя:

Перед покупкой рекомендуется визуально сверить дизайн диска с нужной вам моделью.

Для установки необходимы стандартные шины соответствующего размера (например, 225/60 R18).

Для гарантии идеальной посадки и балансировки установку рекомендуется проводить в специализированном сервисе.

📦 Комплектация

Легкосплавный диск (колесный обод) для Toyota RAV4 × 1 шт.

Стандартные крепежные болты/гайки и колпак ступицы в комплект НЕ входят и приобретаются отдельно.

🔍 Ключевые слова
диск для Toyota RAV4 18 дюймов
колесный диск 5x114.3 ET35
легкосплавный диск RAV4 Rongfang
оригинальный диск Toyota
диск D60.1
колесо на RAV4 18
запасной диск
комплект дисков RAV4
PCD 5/114.3
ступичный размер 60.1

🏷 Хэштеги
#ToyotaRAV4 #ДискиДляToyota #ЛегкосплавныеДиски #RAV4 #КолесныеДиски #ТюнингАвто #Автозапчасти #Диски18 #5x1143 #АвтоАксессуары

【生成模板】
请严格按照以下格式生成内容：

===标题===
[优化后的俄语产品标题]
（短版：[短版俄语产品标题]）

---

🇷🇺 Краткое описание
[简短描述]

---

🇷🇺 Подробное описание
[详细描述，包含特点、优势等]

---

🔍 Ключевые слова
[关键词列表，每行一个]

---

🏷 Хэштеги
[10个相关的俄语标签，每个标签以 # 开头，用空格分隔]

===标签===
[10个相关的俄语标签，每个标签以 # 开头，用空格分隔]

===描述===
[详细描述]

请确保生成的内容：
1. 标题包含主要关键词，吸引人且符合 Ozon 平台规范
2. 标题里不能带有符号：— «»
3. 标签与产品高度相关，有助于搜索和分类
4. 描述详细准确，突出产品特点和优势
5. 所有内容均为俄语
6. 结合 Yandex 热词，提高搜索排名
7. 标题禁止出现原创性、编造或不存在的俄语词汇，只能使用常见、可理解、标准俄语表达
8. 标题采用简短表达，避免过长
9. 禁止引入与输入信息无关的品牌/IP/角色名；若信息不足，用通用描述，不要猜测
10. 标题和描述必须围绕【当前标题/关键词/属性】中的核心名词，不得跑题
11. 标题中禁止出现词语：Оригинальные
`;
}

// 解析 AI 响应
function parseAiResponse(text) {
  try {
    console.log('开始解析 AI 响应:', text);
    
    const result = {
      title: '',
      short_title: '',
      short_description: '',
      long_description: '',
      keywords: [],
      hashtags: []
    };

    // 解析标题部分（新格式）
    const titleMatch = text.match(/===标题===\s*([\s\S]*?)（短版：([^)]+)）/i);
    if (titleMatch) {
      result.title = normalizeTitleText(titleMatch[1]);
      result.short_title = normalizeTitleText(titleMatch[2]);
      console.log('解析到标题（已过滤中文字符）:', result.title);
      console.log('解析到短版标题（已过滤中文字符）:', result.short_title);
    } else {
      // 回退到旧格式解析
      const oldTitleMatch = text.match(/===标题===\s*([\s\S]*?)===标签===/i);
      if (oldTitleMatch) {
        result.title = normalizeTitleText(oldTitleMatch[1]);
        result.short_title = result.title.substring(0, 50) + '...';
        console.log('解析到标题（旧格式，已过滤中文字符）:', result.title);
      }
    }

    // 解析简短描述
    const shortDescMatch = text.match(/🇷🇺 Краткое описание\s*([\s\S]*?)---/i);
    if (shortDescMatch) {
      result.short_description = shortDescMatch[1].trim();
      console.log('解析到简短描述:', result.short_description.substring(0, 100) + '...');
    }

    // 解析详细描述
    const longDescMatch = text.match(/🇷🇺 Подробное описание\s*([\s\S]*?)---\s*🔍 Ключевые слова/i);
    if (longDescMatch) {
      result.long_description = longDescMatch[1].trim();
      console.log('解析到详细描述:', result.long_description.substring(0, 100) + '...');
    } else {
      // 回退到旧格式解析
      const oldDescMatch = text.match(/===描述===\s*([\s\S]*)$/i);
      if (oldDescMatch) {
        result.long_description = oldDescMatch[1].trim();
        console.log('解析到描述（旧格式）:', result.long_description.substring(0, 100) + '...');
      }
    }

    // 解析关键词
    const keywordsMatch = text.match(/🔍 Ключевые слова\s*([\s\S]*?)---\s*🏷 Хэштеги/i);
    if (keywordsMatch) {
      const keywordsText = keywordsMatch[1].trim();
      result.keywords = keywordsText.split('\n').filter(word => word.trim()).slice(0, 10);
      console.log('解析到关键词:', result.keywords);
    } else if (!result.keywords.length) {
      // 从标题和描述中提取关键词
      if (result.title || result.long_description) {
        const allText = (result.title + ' ' + result.long_description).toLowerCase();
        const words = allText.match(/\b\w+\b/g) || [];
        // 简单去重和过滤
        const uniqueWords = [...new Set(words)].filter(word => word.length > 2);
        result.keywords = uniqueWords.slice(0, 10);
        console.log('提取到关键词:', result.keywords);
      }
    }

    // 解析标签（新格式）
    const hashtagsMatch = text.match(/🏷 Хэштеги\s*([\s\S]*?)(===标签===|$)/i);
    if (hashtagsMatch) {
      const hashtagsText = hashtagsMatch[1].trim();
      result.hashtags = hashtagsText.match(/#[^\s#]+/g) || [];
      console.log('解析到标签（新格式）:', result.hashtags);
    } else {
      // 回退到旧格式解析
      const oldTagsMatch = text.match(/===标签===\s*([\s\S]*?)===描述===/i);
      if (oldTagsMatch) {
        const oldTagsText = oldTagsMatch[1].trim();
        result.hashtags = oldTagsText.match(/#[^\s#]+/g) || [];
        console.log('解析到标签（旧格式）:', result.hashtags);
      }
    }

    // 如果没有解析到内容，使用模拟数据
    if (!result.title) {
      console.log('未解析到内容，使用模拟数据');
      return {
        title: "Латексная маска для косплея Avatar 3, хэллоуинская косплей маска, высокого качества",
        short_title: "Косплей маска Avatar 3 — латекс, высокое качество",
        short_description: "Теплая и удобная латексная маска для косплея. Подходит для праздников, мероприятий и фотосессий.",
        long_description: "Качественная латексная косплей маска из мягкого материала. Надежная посадка, комфорт и эффектный внешний вид для ярких образов. Подходит для хэллоуина, косплей-мероприятий и тематических вечеринок.",
        keywords: ["косплей маска", "маска для праздника", "маска avatar", "карнавальная маска"],
        hashtags: ["#Avatar3", "#косплей", "#маска", "#хэллоуин", "#косплей-маска", "#фильм", "#праздник", "#текстиль", "#шоу", "#фанатский-товар"]
      };
    }

    return result;
  } catch (error) {
    console.error('解析 AI 响应错误:', error);
    // 解析错误时使用模拟数据
    return {
      title: "Латексная маска для косплея Avatar 3, хэллоуинская косплей маска, высокого качества",
      short_title: "Косплей маска Avatar 3 — латекс, высокое качество",
      short_description: "Теплая и удобная латексная маска для косплея. Подходит для праздников, мероприятий и фотосессий.",
      long_description: "Качественная латексная косплей маска из мягкого материала. Надежная посадка, комфорт и эффектный внешний вид для ярких образов. Подходит для хэллоуина, косплей-мероприятий и тематических вечеринок.",
      keywords: ["косплей маска", "маска для праздника", "маска avatar", "карнавальная маска"],
      hashtags: ["#Avatar3", "#косплей", "#маска", "#хэллоуин", "#косплей-маска", "#фильм", "#праздник", "#текстиль", "#шоу", "#фанатский-товар"]
    };
  }
}

// 调用 Qwen AI 接口（通过后台脚本）
async function callQwenAI(prompt) {
  return new Promise((resolve, reject) => {
    console.log('通过后台脚本调用 Qwen AI，提示词:', prompt.substring(0, 100) + '...');
    
    // 检查插件上下文是否有效
    if (!chrome.runtime || !chrome.runtime.sendMessage) {
      console.error('插件上下文无效，可能已被重新加载');
      reject(new Error('插件上下文无效，请刷新页面后重试'));
      return;
    }
    
    try {
      // 向后台脚本发送消息
      chrome.runtime.sendMessage(
        { action: 'callQwenAI', prompt },
        (response) => {
          console.log('收到后台脚本的响应:', response);
          
          if (chrome.runtime.lastError) {
            console.error('后台脚本通信错误:', chrome.runtime.lastError);
            // 检查是否是上下文无效错误
            if (chrome.runtime.lastError.message.includes('Extension context invalidated')) {
              reject(new Error('插件上下文无效，请刷新页面后重试'));
            } else {
              reject(new Error('与后台脚本通信失败'));
            }
            return;
          }
          
          if (response.success) {
            resolve(response.result);
          } else {
            reject(new Error(response.error || 'Qwen AI 调用失败'));
          }
        }
      );
    } catch (error) {
      console.error('发送消息时出错:', error);
      if (error.message.includes('Extension context invalidated')) {
        reject(new Error('插件上下文无效，请刷新页面后重试'));
      } else {
        reject(new Error('调用 AI 时出错: ' + error.message));
      }
    }
  });
}

// 自动回填标题
function fillTitle(title) {
  return new Promise((resolve, reject) => {
    const titleInput = document.querySelector(CONFIG.selectors.title);
    if (!titleInput) {
      reject(new Error('找不到标题输入框'));
      return;
    }

    titleInput.value = title;
    titleInput.dispatchEvent(new Event('input', { bubbles: true }));
    titleInput.dispatchEvent(new Event('change', { bubbles: true }));
    resolve();
  });
}

// 自动回填标签
function fillTags(tags) {
  return new Promise((resolve, reject) => {
    let tagInput = findTagsInput();

    if (!tagInput) {
      reject(new Error('找不到标签输入框'));
      return;
    }

    const tagsText = tags.join(' ');
    simulateInputText(tagInput, tagsText);
    resolve();
  });
}

function findTagsInput() {
  const inputs = Array.from(document.querySelectorAll(CONFIG.selectors.tagsInputs));
  // 1) 已包含 # 的输入框优先
  let tagInput = inputs.find((input) => (input.value || '').includes('#'));
  if (tagInput) {
    return tagInput;
  }

  // 2) 根据标签文本定位
  const labelNodes = Array.from(document.querySelectorAll('label, div, span'))
    .filter((el) => el.textContent && (el.textContent.includes('标签') || el.textContent.includes('Tags') || el.textContent.includes('Хэштеги') || el.textContent.includes('Теги')));
  for (const label of labelNodes) {
    const formRow = label.closest('.ant-form-item-row') || label.closest('.ant-form-item') || label.closest('div');
    if (formRow) {
      const candidate = formRow.querySelector('input[type="text"], textarea');
      if (candidate) {
        return candidate;
      }
    }
  }

  // 3) 兜底：找第一个可编辑的输入框（排除标题/型号/颜色）
  tagInput = inputs.find((input) => {
    if (input.disabled || input.readOnly) {
      return false;
    }
    if (CONFIG.selectors.title && input.matches(CONFIG.selectors.title)) {
      return false;
    }
    if (CONFIG.selectors.skuModelTarget && input.matches(CONFIG.selectors.skuModelTarget)) {
      return false;
    }
    return true;
  });
  return tagInput || null;
}

// 查找描述输入框
function findDescriptionTargets() {
  const targets = {
    short: null,
    long: null
  };

  if (CONFIG.selectors.shortDescription) {
    targets.short = document.querySelector(CONFIG.selectors.shortDescription);
  }
  if (CONFIG.selectors.longDescription) {
    targets.long = document.querySelector(CONFIG.selectors.longDescription);
  }

  if (!targets.short || !targets.long) {
    const candidates = Array.from(
      document.querySelectorAll('textarea, [contenteditable="true"]')
    );
    if (candidates.length === 1) {
      targets.long = targets.long || candidates[0];
    } else if (candidates.length >= 2) {
      targets.short = targets.short || candidates[0];
      targets.long = targets.long || candidates[1];
    }
  }

  return targets;
}

function clearDescriptionFields() {
  const targets = findDescriptionTargets();
  [targets.short, targets.long].forEach((target) => {
    if (!target) {
      return;
    }
    if ('value' in target) {
      target.value = '';
    } else {
      target.innerText = '';
    }
    target.dispatchEvent(new Event('input', { bubbles: true }));
    target.dispatchEvent(new Event('change', { bubbles: true }));
  });
}

// 回填描述
function fillDescriptions(shortDescription, longDescription) {
  return new Promise(async (resolve, reject) => {
    const targets = findDescriptionTargets();
    if (!targets.short && !targets.long) {
      reject(new Error('找不到描述输入框'));
      return;
    }

    if (targets.short && shortDescription) {
      if ('value' in targets.short) {
        targets.short.value = shortDescription;
      } else {
        targets.short.innerText = shortDescription;
      }
      targets.short.dispatchEvent(new Event('input', { bubbles: true }));
      targets.short.dispatchEvent(new Event('change', { bubbles: true }));
    }

    if (longDescription) {
      const jsonDescription = buildJsonDescription(longDescription);
      const updated = await openJsonEditorAndSet(jsonDescription);
      if (!updated && targets.long) {
        // fallback: 直接回填到描述输入框
        if ('value' in targets.long) {
          targets.long.value = jsonDescription;
        } else {
          targets.long.innerText = jsonDescription;
        }
        targets.long.dispatchEvent(new Event('input', { bubbles: true }));
        targets.long.dispatchEvent(new Event('change', { bubbles: true }));
      }
    }

    resolve();
  });
}

function findButtonByText(text) {
  const buttons = Array.from(document.querySelectorAll('button'));
  return buttons.find((btn) => (btn.textContent || '').replace(/\s+/g, '') === text.replace(/\s+/g, ''));
}

function findJsonEditorInput(root = document) {
  const textarea = root.querySelector('textarea');
  if (textarea) {
    return textarea;
  }
  const contentEditable = root.querySelector('[contenteditable="true"]');
  if (contentEditable) {
    return contentEditable;
  }
  return null;
}

function findDialogRoot() {
  const dialogs = Array.from(document.querySelectorAll('.ant-modal, [role="dialog"]'));
  if (dialogs.length === 0) {
    return null;
  }
  return dialogs[dialogs.length - 1];
}

function clickConfirmInDialog(dialogRoot) {
  const buttons = Array.from(dialogRoot.querySelectorAll('button'));
  const confirm = buttons.find((btn) => (btn.textContent || '').replace(/\s+/g, '') === '确定');
  if (confirm) {
    confirm.click();
    return true;
  }
  return false;
}

async function openJsonEditorAndSet(value) {
  try {
    const editJsonButton = findButtonByText('编辑JSON代码');
    if (!editJsonButton) {
      return false;
    }
    editJsonButton.click();

    // 等待编辑器出现
    const editor = await retry(() => new Promise((resolve, reject) => {
      const dialog = findDialogRoot();
      const input = dialog ? findJsonEditorInput(dialog) : findJsonEditorInput();
      if (input) {
        resolve(input);
      } else {
        reject(new Error('JSON 编辑器未出现'));
      }
    }), 6, 300);

    if ('value' in editor) {
      editor.value = '';
      editor.dispatchEvent(new Event('input', { bubbles: true }));
      editor.value = value;
    } else {
      editor.innerText = '';
      editor.dispatchEvent(new Event('input', { bubbles: true }));
      editor.innerText = value;
    }
    editor.dispatchEvent(new Event('input', { bubbles: true }));
    editor.dispatchEvent(new Event('change', { bubbles: true }));

    const dialog = findDialogRoot();
    if (dialog) {
      clickConfirmInDialog(dialog);
    }
    return true;
  } catch (error) {
    console.warn('打开 JSON 编辑器失败:', error);
    return false;
  }
}

function buildJsonDescription(text) {
  const lines = String(text || '')
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map((line) => line.trim());
  const contentLines = lines.length > 0 ? lines : [''];
  const payload = {
    content: [
      {
        gapSize: 'm',
        padding: 'type2',
        title: { align: 'left', color: 'color1', content: [], size: 'size5' },
        theme: 'default',
        text: { align: 'left', color: 'color1', content: contentLines, size: 'size2' },
        widgetName: 'raTextBlock'
      }
    ],
    version: 0.3
  };
  return JSON.stringify(payload);
}

// 检查扩展上下文是否有效
function checkExtensionContext() {
  if (!chrome.runtime || !chrome.runtime.sendMessage) {
    throw new Error('插件上下文无效，请刷新页面后重试');
  }
}

// 过滤中文字符、标签和替换特殊符号
function removeChineseCharacters(text) {
  return text
    .replace(/[\u4e00-\u9fa5]/g, '') // 过滤中文字符
    .replace(/#[^\s#]+/g, '') // 过滤标签
    .replace(/—/g, '-') // 长破折号换成短破折号
    .replace(/«/g, '<') // 左双引号换成小于号
    .replace(/»/g, '>') // 右双引号换成大于号
    .replace(/\s+/g, ' ') // 合并多个空格为单个空格
    .trim();
}

// 规范化标题文本，确保只取第一行有效标题
function normalizeTitleText(text) {
  if (!text) {
    return '';
  }
  const lines = String(text)
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
  const firstLine = lines.length > 0 ? lines[0] : String(text).trim();
  const cleaned = removeChineseCharacters(firstLine);
  return formatRussianTitle(cleaned);
}

// 根据关键词对俄语标题做轻量断句（逗号/连词）
function formatRussianTitle(title) {
  if (!title) {
    return '';
  }
  let result = title
    .replace(/\s+/g, ' ')
    .replace(/\s+,/g, ',')
    .replace(/,\s*,/g, ',')
    .trim();

  // 在常见分隔短语前加逗号，避免一长串
  const commaBefore = [
    ' украшение',
    ' декор',
    ' тематическая вечеринка',
    ' для дома',
    ' для семьи',
    ' карнавал',
    ' хэллоуин',
    ' косплей',
    ' детский костюм',
    ' для фотосессии'
  ];

  commaBefore.forEach((phrase) => {
    const re = new RegExp(`\\s${phrase}`, 'gi');
    result = result.replace(re, `,${phrase}`);
  });

  // 处理“для ... и ...”的连词一致性
  result = result.replace(/,? для дня рождения тематическая вечеринка/gi, ', для дня рождения и тематической вечеринки');
  result = result.replace(/,? карнавал хэллоуин косплей/gi, ', карнавал, хэллоуин, косплей');

  return result.replace(/,\s*,/g, ',').replace(/\s+,/g, ',').trim();
}

function containsChinese(text) {
  return /[\u4e00-\u9fa5]/.test(text || '');
}

// 查找颜色名称输入框
function findColorNameInputs() {
  const inputs = [];
  // 优先根据颜色名称表头定位，并在同一表格/模块内找输入框
  const headerNodes = Array.from(document.querySelectorAll('.sku-main-header-th, th, div, span'))
    .filter((el) => el.textContent && (el.textContent.includes('颜色名称') || el.textContent.includes('Название цвета')));
  headerNodes.forEach((header) => {
    const tableScope =
      header.closest('table') ||
      header.closest('thead')?.parentElement ||
      header.closest('.sku') ||
      header.closest('.sku-table') ||
      header.closest('.sku-main');

    const scope = tableScope || header.closest('div');
    if (!scope) {
      return;
    }

    scope.querySelectorAll('input[type="text"]').forEach((input) => {
      if (CONFIG.selectors.title && input.matches(CONFIG.selectors.title)) {
        return;
      }
      // 移除对 '#' 的检查，允许颜色名称包含 '#'
      // if ((input.value || '').includes('#')) {
      //   return;
      // }
      if (CONFIG.selectors.skuModelTarget && input.matches(CONFIG.selectors.skuModelTarget)) {
        return;
      }
      if (!inputs.includes(input)) {
        inputs.push(input);
      }
    });
  });

  const labelNodes = Array.from(document.querySelectorAll('div, label, span'))
    .filter((el) => el.textContent && (el.textContent.includes('Название цвета') || el.textContent.includes('颜色名称')));

  const seen = new Set();

  labelNodes.forEach((label) => {
    let container = null;
    let current = label.parentElement;
    let depth = 0;
    while (current && depth < 6) {
      const found = current.querySelectorAll('input[type="text"]');
      if (found.length > 0) {
        container = current;
        break;
      }
      current = current.parentElement;
      depth += 1;
    }

    if (container) {
      container.querySelectorAll('input[type="text"]').forEach((input) => {
        if (CONFIG.selectors.title && input.matches(CONFIG.selectors.title)) {
          return;
        }
        // 移除对 '#' 的检查，允许颜色名称包含 '#'
        // if ((input.value || '').includes('#')) {
        //   return;
        // }
        if (CONFIG.selectors.skuModelTarget && input.matches(CONFIG.selectors.skuModelTarget)) {
          return;
        }
        if (!seen.has(input)) {
          seen.add(input);
          inputs.push(input);
        }
      });
      return;
    }

    // fallback: 向下查找相邻区域的输入框
    let sibling = label.parentElement ? label.parentElement.nextElementSibling : null;
    let steps = 0;
    while (sibling && steps < 8) {
      sibling.querySelectorAll('input[type="text"]').forEach((input) => {
        if (CONFIG.selectors.title && input.matches(CONFIG.selectors.title)) {
          return;
        }
        if ((input.value || '').includes('#')) {
          return;
        }
        if (CONFIG.selectors.skuModelTarget && input.matches(CONFIG.selectors.skuModelTarget)) {
          return;
        }
        if (!seen.has(input)) {
          seen.add(input);
          inputs.push(input);
        }
      });
      if (inputs.length > 0) {
        break;
      }
      sibling = sibling.nextElementSibling;
      steps += 1;
    }
  });

  return inputs;
}

function fillColorNameInput(element, value) {
  if (!element) {
    return;
  }
  simulateInputText(element, value);
}

function simulateInputText(element, value) {
  element.focus();
  if ('value' in element) {
    const setter = Object.getOwnPropertyDescriptor(element.__proto__, 'value')?.set;
    if (setter) {
      setter.call(element, '');
      element.dispatchEvent(new Event('input', { bubbles: true }));
      setter.call(element, value);
    } else {
      element.value = '';
      element.dispatchEvent(new Event('input', { bubbles: true }));
      element.value = value;
    }
  } else {
    element.innerText = '';
    element.dispatchEvent(new Event('input', { bubbles: true }));
    element.innerText = value;
  }
  element.dispatchEvent(new Event('input', { bubbles: true }));
  element.dispatchEvent(new Event('change', { bubbles: true }));
}

function truncateChineseTo(text, maxChinese) {
  if (!text) {
    return '';
  }
  let count = 0;
  let result = '';
  for (const ch of String(text)) {
    if (/[\u4e00-\u9fa5]/.test(ch)) {
      count += 1;
      if (count > maxChinese) {
        break;
      }
    }
    result += ch;
  }
  return result;
}

function findSkuPrefixValue() {
  const labelNodes = Array.from(document.querySelectorAll('div, label, span'))
    .filter((el) => el.textContent && el.textContent.includes('SKU前缀'));
  for (const label of labelNodes) {
    let current = label.parentElement;
    let depth = 0;
    while (current && depth < 6) {
      const input = current.querySelector('input[type="text"], input');
      if (input && input.value) {
        return input.value.trim();
      }
      current = current.parentElement;
      depth += 1;
    }
  }
  const named = document.querySelector('input[name*="skuPrefix" i], input[id*="skuPrefix" i]');
  if (named && named.value) {
    return named.value.trim();
  }
  return '';
}

function findFirstSkuValue() {
  const inputs = Array.from(document.querySelectorAll('input[type="text"], input'))
    .filter((input) => input.value && /sku/i.test(input.name || '') || /sku/i.test(input.id || ''));
  if (inputs.length > 0) {
    return inputs[0].value.trim();
  }
  const byLabel = Array.from(document.querySelectorAll('div, label, span'))
    .filter((el) => el.textContent && /\bSKU\b/i.test(el.textContent));
  for (const label of byLabel) {
    let current = label.parentElement;
    let depth = 0;
    while (current && depth < 6) {
      const input = current.querySelector('input[type="text"], input');
      if (input && input.value) {
        return input.value.trim();
      }
      current = current.parentElement;
      depth += 1;
    }
  }
  return '';
}

async function fillSkuFields() {
  let skuPrefix = findSkuPrefixValue();
  if (!skuPrefix) {
    skuPrefix = window.prompt('请输入 SKU 前缀：', '');
  }
  const colorInputs = findColorNameInputs();
  const variants = colorInputs
    .map((input) => ('value' in input ? input.value : input.innerText))
    .map((value) => truncateChineseTo(String(value || '').trim(), 5))
    .filter(Boolean);
  const suffix = variants.length > 0 ? variants.join('/') : '';
  const skuModelValue = skuPrefix ? (suffix ? `${skuPrefix}-${suffix}` : skuPrefix) : '';

  const generateBtn = findByTextSelector('span', '一键生成');
  if (generateBtn) {
    generateBtn.click();
  }

  const skuPrefixTarget = document.querySelector('input[name="skuPrefix"]');
  if (skuPrefixTarget && skuPrefix) {
    simulateInputText(skuPrefixTarget, skuPrefix);
  }

  const setBtn = findByTextSelector('button', '设置');
  if (setBtn) {
    setBtn.click();
  }

  const skuModelTarget = await findModelNameInput() || await waitForElement(CONFIG.selectors.skuModelTarget, 6, 300);
  if (skuModelTarget && skuPrefix) {
    if (skuModelTarget.classList.contains('ant-input-status-success')) {
      console.warn('检测到命名模板用的型号名称输入框，跳过填充');
      return;
    }
    simulateInputText(skuModelTarget, skuPrefix);
  }
}

async function fillExtraSmallPackageSize() {
  // deprecated: use fillLogisticsPackageSize instead
  return;
}

async function getLogisticsSetting() {
  return new Promise((resolve) => {
    chrome.storage.local.get(['qwenLogistics'], (result) => {
      resolve(result.qwenLogistics || 'none');
    });
  });
}

async function fillLogisticsPackageSize(logistics) {
  if (logistics !== 'extra_small') {
    return;
  }

  let batchTrigger = null;
  const sizeHeader = Array.from(document.querySelectorAll('th, div, span'))
    .find((el) => (el.textContent || '').replace(/\s+/g, '') === '尺寸(mm)');
  if (sizeHeader) {
    const th = sizeHeader.closest('th');
    if (th) {
      batchTrigger = Array.from(th.querySelectorAll('span'))
        .find((el) => (el.textContent || '').replace(/\s+/g, '') === '批量');
    }
  }
  if (!batchTrigger) {
    batchTrigger = findByTextSelector('span', '批量');
  }
  if (batchTrigger) {
    batchTrigger.click();
  }

  const lengthInput = await waitForElement('input[name="packageLength"]', 8, 200);
  const widthInput = await waitForElement('input[name="packageWidth"]', 8, 200);
  const heightInput = await waitForElement('input[name="packageHeight"]', 8, 200);
  if (lengthInput && widthInput && heightInput) {
    simulateInputText(lengthInput, '200');
    simulateInputText(widthInput, '100');
    simulateInputText(heightInput, '30');
  }

  const sizeDialog = findDialogRoot();
  if (sizeDialog) {
    clickConfirmInDialog(sizeDialog);
  }

  // 重量批量
  let weightBatch = null;
  const weightHeader = Array.from(document.querySelectorAll('th, div, span'))
    .find((el) => (el.textContent || '').replace(/\s+/g, '') === '重量(g)');
  if (weightHeader) {
    const th = weightHeader.closest('th');
    if (th) {
      weightBatch = Array.from(th.querySelectorAll('span'))
        .find((el) => (el.textContent || '').replace(/\s+/g, '') === '批量');
    }
  }
  if (!weightBatch) {
    weightBatch = findByTextSelector('span', '批量');
  }
  if (weightBatch) {
    weightBatch.click();
  }

  const weightInput = await waitForElement('input[placeholder*="重量"], input[name="packageWeight"], input[name="inputName"]', 8, 200);
  if (weightInput) {
    simulateInputText(weightInput, '500');
  }

  const weightDialog = findDialogRoot();
  if (weightDialog) {
    clickConfirmInDialog(weightDialog);
  } else {
    const confirmBtn = findByTextSelector('button', '确定');
    if (confirmBtn) {
      confirmBtn.click();
    }
  }
}

function findByTextSelector(tag, text) {
  const nodes = Array.from(document.querySelectorAll(tag));
  return nodes.find((node) => (node.textContent || '').replace(/\s+/g, '') === text.replace(/\s+/g, ''));
}

function waitForElement(selector, retries = 5, delay = 300) {
  return new Promise((resolve) => {
    const existing = document.querySelector(selector);
    if (existing) {
      resolve(existing);
      return;
    }
    let attempts = 0;
    const timer = setInterval(() => {
      const found = document.querySelector(selector);
      if (found || attempts >= retries) {
        clearInterval(timer);
        resolve(found || null);
      }
      attempts += 1;
    }, delay);
  });
}


async function findModelNameInput() {
  const labelNodes = Array.from(document.querySelectorAll('label, div, span'))
    .filter((el) => el.textContent && (el.textContent.includes('合并属性') || el.textContent.includes('型号名称')));
  for (const label of labelNodes) {
    // 从“型号名称”标签向下严格找对应输入框
    let container = label.closest('div');
    let depth = 0;
    while (container && depth < 6) {
      const next = container.nextElementSibling;
      if (next) {
        const inputInNext = next.querySelector('div.text-input-item input[data-v-712f6a66].input-item');
        if (inputInNext) {
          return inputInNext;
        }
      }
      container = container.parentElement;
      depth += 1;
    }
  }
  return null;
}

async function translateTextToEnglish(text) {
  const prompt = `Translate the following text to English. Output only the translation, no quotes or extra text.\n\n${text}`;
  const raw = await callQwenAI(prompt);
  if (typeof raw !== 'string') {
    return text;
  }
  return raw
    .replace(/^"+|"+$/g, '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)[0] || text;
}

// 优化颜色名称：超过10个字符时自动缩减到10个
function optimizeColorName(name) {
  if (!name) return name;
  
  // 检查总字符长度
  if (name.length > 10) {
    const result = name.substring(0, 10).trim();
    console.log('颜色名称过长，已缩减:', name, '->', result);
    return result;
  }
  
  return name;
}

function collectChineseColorValues(inputs) {
  const items = [];
  inputs.forEach((element, index) => {
    const value = 'value' in element ? element.value : element.innerText;
    if (value && containsChinese(value)) {
      // 优化颜色名称长度
      const optimizedValue = optimizeColorName(value);
      items.push({ index, value: optimizedValue });
    }
  });
  return items;
}

async function batchTranslateToEnglish(values) {
  const prompt = `Translate each line to English. Output only translated lines in the same order, one per line. No numbering.\n\n${values.join('\n')}`;
  const raw = await callQwenAI(prompt);
  if (typeof raw !== 'string') {
    return values;
  }
  const lines = raw
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
  if (lines.length !== values.length) {
    return values;
  }
  return lines;
}

// 主流程：先授权 -> 读取 DOM -> 调用 AI -> 回填
async function generateAllContentAndFill() {
  try {
    // 设置生成状态为进行中
    isGenerating = true;
    
    await waitForDOMLoad();
    
    // 显示正在生成的通知
    showNotification('处理中', '正在准备生成内容...');
    console.log('步骤 1: 准备读取产品信息');
    
    // 检查上下文有效性
    checkExtensionContext();
    
    // 检查上下文有效性
    checkExtensionContext();
    
    // 读取页面信息
    showNotification('处理中', '正在读取产品信息...');
    console.log('步骤 2: 读取网页内容');
    
    const domData = await retry(() => readDOM());
    console.log('读取的 DOM 数据:', domData);
    
    // 检查上下文有效性
    checkExtensionContext();

    // 读取完成后，清空当前产品描述内容
    clearDescriptionFields();

    // 物流方式：按设置批量填充包装尺寸
    const logisticsSetting = await getLogisticsSetting();
    await fillLogisticsPackageSize(logisticsSetting);

    // 若颜色名称为中文，先翻译成英文并回填（在填充 SKU 前执行）
    const colorInputs = findColorNameInputs();
    const colorItems = collectChineseColorValues(colorInputs);
    if (colorItems.length > 0) {
      showNotification('处理中', '正在翻译颜色名称...');
      try {
        // 确保至少有一个颜色值需要翻译
        const sourceValues = colorItems.map((item) => item.value).filter(Boolean);
        if (sourceValues.length > 0) {
          console.log('开始翻译颜色名称:', sourceValues);
          const translatedValues = await batchTranslateToEnglish(sourceValues);
          
          // 确保翻译结果有效
          if (Array.isArray(translatedValues) && translatedValues.length > 0) {
            colorItems.forEach((item, idx) => {
              const translated = translatedValues[idx] || item.value;
              const targetInput = colorInputs[item.index];
              if (targetInput) {
                fillColorNameInput(targetInput, translated);
                console.log('颜色名称已翻译:', item.value, '->', translated);
              }
            });
            // 更新第一个颜色名称回传给提示词
            domData.colorName = translatedValues[0] || domData.colorName;
            console.log('颜色名称翻译完成，更新提示词颜色为:', domData.colorName);
          } else {
            console.warn('翻译结果无效，使用原始颜色名称');
            // 即使翻译失败，也更新颜色名称为第一个原始颜色
            domData.colorName = sourceValues[0] || domData.colorName;
          }
        } else {
          console.warn('无有效颜色值需要翻译');
        }
      } catch (translateError) {
        console.warn('颜色名称翻译失败，使用原始颜色名称:', translateError);
        // 翻译失败时，使用第一个原始颜色名称
        if (colorItems.length > 0) {
          domData.colorName = colorItems[0].value || domData.colorName;
          console.log('翻译失败，使用原始颜色名称:', domData.colorName);
        }
      }
    } else {
      console.log('未找到需要翻译的中文颜色名称');
    }

    // 填充 SKU 前缀与型号（在颜色翻译后执行）
    await fillSkuFields();

    // 构建提示词并调用 AI
    showNotification('处理中', '正在生成产品内容...');
    console.log('步骤 3: 构建提示词并调用 AI');
    
    const yandexHotWords = getYandexHotWords();
    const prompt = buildPrompt(domData, yandexHotWords);
    
    try {
      // 检查上下文有效性
      checkExtensionContext();
      
      const result = await callQwenAI(prompt);
      console.log('AI 生成的结果:', result);

      const parsedResult = typeof result === 'string' ? parseAiResponse(result) : result;
      if (parsedResult && parsedResult.title) {
        parsedResult.title = normalizeTitleText(parsedResult.title);
      }
      if (parsedResult && parsedResult.short_title) {
        parsedResult.short_title = normalizeTitleText(parsedResult.short_title);
      }
      
      // 检查上下文有效性
      checkExtensionContext();
      
      // 检查是否是真实的 AI 响应（不是模拟数据）
      if (parsedResult && parsedResult.title && parsedResult.hashtags && parsedResult.hashtags.length > 0) {
        // 回填内容
        console.log('步骤 4: 回填生成的内容');
        
        if (parsedResult.title) {
          await fillTitle(parsedResult.title);
        }
        
        let tagsToFill = [];
        if (Array.isArray(parsedResult.hashtags) && parsedResult.hashtags.length > 0) {
          tagsToFill = parsedResult.hashtags;
        } else if (Array.isArray(parsedResult.keywords) && parsedResult.keywords.length > 0) {
          tagsToFill = parsedResult.keywords.map((kw) => (kw.startsWith('#') ? kw : `#${kw}`));
        }
        
        if (tagsToFill.length > 0) {
          await fillTags(tagsToFill);
        }
        
        await fillDescriptions(parsedResult.short_description, parsedResult.long_description);
        console.log('标题、标签和描述已成功回填');
        
        showNotification('成功', 'AI 内容生成并回填成功');
      } else {
        console.log('未获取到有效的 AI 响应，跳过回填');
        showNotification('提示', '未获取到有效的 AI 响应，请检查网络连接或 Qwen AI 授权状态');
      }
    } catch (aiError) {
      console.error('AI 调用失败:', aiError);
      if (aiError.message.includes('未设置 Qwen API Key')) {
        // 显示更友好的错误提示，指导用户如何配置 API Key
        showNotification('错误', '未设置 Qwen API Key，请点击插件图标并在设置界面中配置');
      } else if (aiError.message.includes('插件上下文无效')) {
        showNotification('错误', '插件上下文已失效，请刷新页面后重试');
      } else {
        showNotification('错误', 'AI 调用失败，请检查网络连接或重试');
      }
    }
  } catch (error) {
    console.error('错误:', error);
    // 授权失败的错误已经在 callQwenAI 中处理
    if (!error.message.includes('授权失败')) {
      if (error.message.includes('插件上下文无效')) {
        showNotification('错误', '插件上下文已失效，请刷新页面后重试');
      } else {
        showNotification('错误', error.message);
      }
    }
  } finally {
    // 无论成功失败，都更新状态
    isGenerating = false;
  }
}

// 手动触发生成
async function manualGenerateAll() {
  await generateAllContentAndFill();
}

// 显示通知
function showNotification(title, message) {
  if (!CONFIG.showNotifications) {
    return;
  }
  
  // 创建通知元素
  const notification = document.createElement('div');
  notification.style.cssText = `
    position: fixed;
    top: 20px;
    right: 20px;
    padding: 15px 20px;
    border-radius: 4px;
    color: white;
    font-size: 14px;
    z-index: 9999;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
    transition: all 0.3s ease;
  `;
  
  if (title === '成功') {
    notification.style.backgroundColor = '#52c41a';
  } else {
    notification.style.backgroundColor = '#f5222d';
  }
  
  notification.textContent = message;
  document.body.appendChild(notification);
  
  // 3 秒后移除通知
  setTimeout(() => {
    notification.style.opacity = '0';
    setTimeout(() => {
      document.body.removeChild(notification);
    }, 300);
  }, 3000);
}

// 添加悬浮按钮
function addFloatingButton() {
  const container = document.createElement('div');
  container.style.cssText = `
    position: fixed;
    bottom: 40px;
    right: 40px;
    z-index: 9999;
  `;

  // AI 生成按钮
  const aiButton = document.createElement('button');
  aiButton.textContent = 'AI 生成';
  aiButton.style.cssText = `
    padding: 12px 20px;
    background-color: #1890ff;
    color: white;
    border: none;
    border-radius: 4px;
    font-size: 14px;
    cursor: pointer;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
    transition: all 0.3s ease;
    width: 150px;
  `;

  // 添加事件监听器 - 触发内容生成
  aiButton.addEventListener('click', manualGenerateAll);

  // 添加悬停效果
  aiButton.addEventListener('mouseenter', () => {
    aiButton.style.transform = 'translateY(-2px)';
  });
  
  aiButton.addEventListener('mouseleave', () => {
    aiButton.style.transform = 'translateY(0)';
  });

  // 添加到容器
  container.appendChild(aiButton);

  document.body.appendChild(container);
}

// 回车触发生成（优化版，避免干扰其他功能）
function addEnterKeyTrigger() {
  const handler = (event) => {
    // 检查是否在输入状态
    if (event.isComposing) {
      return;
    }
    
    // 检查是否是纯 Enter 键（无修饰键）
    if (event.key === 'Enter' && !event.shiftKey && !event.ctrlKey && !event.altKey && !event.metaKey) {
      const target = event.target;
      const tag = target && target.tagName ? target.tagName.toLowerCase() : '';
      
      // 检查是否在输入框中
      const isInput = tag === 'input' || tag === 'textarea' || (target && target.getAttribute && target.getAttribute('contenteditable') === 'true');
      if (isInput) {
        return;
      }
      
      // 检查是否在弹出窗口中
      const inModal = target.closest('.ant-modal, [role="dialog"]');
      if (inModal) {
        return;
      }
      
      // 检查是否在重量输入相关区域
      const inWeightArea = target.closest('[data-name*="weight"], [class*="weight"], [id*="weight"]');
      if (inWeightArea) {
        return;
      }
      
      // 移除事件监听器并触发生成
      document.removeEventListener('keydown', handler);
      manualGenerateAll();
    }
  };
  
  // 添加事件监听器
  document.addEventListener('keydown', handler);
}

// 初始化插件
async function initPlugin() {
  // 处理可能的授权回调
  handleAuthCallback();
  
  // 添加悬浮按钮
  addFloatingButton();

  // 回车触发
  addEnterKeyTrigger();
  
  // 自动触发一次生成（可配置）
  if (CONFIG.autoGenerateOnLoad) {
    setTimeout(generateAllContentAndFill, CONFIG.autoGenerateDelayMs);
  }
}

// 启动插件
initPlugin();
